// Jenkinsfile
pipeline {
  agent any
  stages {
    stage('Install') {
      steps { sh 'npm install' }
    }
    stage('Build') {
      steps { sh 'npm run build' }
    }
    stage('Example Run') {
      steps { sh 'npm run example:car' }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: 'artifacts/**/*', fingerprint: true
    }
  }
}
