// src/pages/common/insurance-type-selection/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: common.insurance-type-selection
// scannedAt: 2026-03-09T12:49:52.264Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "common.insurance-type-selection",
  urlPath: "/products",
  urlRe: /\/[a-z0-9]+/i,
  title: "Get a new quote or view saved quotes",
  titleRe: new RegExp("Get a new quote or view saved quotes", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  back: "back" as ElementKey,
  back2: "back2" as ElementKey,
  back3: "back3" as ElementKey,
  carQuote: "carQuote" as ElementKey,
  carQuote2: "carQuote2" as ElementKey,
  homeQuote: "homeQuote" as ElementKey,
  homeQuote2: "homeQuote2" as ElementKey,
  letUsKnow: "letUsKnow" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;