// src/pages/common/insurance-type-selection/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: common.insurance-type-selection
// scannedAt: 2026-03-09T12:49:52.264Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  back: {
    type: "button",
    preferred: "role=button[name=/Back/i]",
    fallbacks: ["text=/Back/i"],
  },
  back2: {
    type: "link",
    preferred: "role=link[name=/Back/i]",
    fallbacks: ["text=/Back/i"],
  },
  back3: {
    type: "button",
    preferred: "role=link[name=/Back/i]",
    fallbacks: ["text=/Back/i"],
  },
  carQuote: {
    type: "link",
    preferred: "css=#viewSavedSubscriptionCarQuotes",
    fallbacks: ["role=link[name=/Car quote/i]", "text=/Car quote/i"],
  },
  carQuote2: {
    type: "button",
    preferred: "role=button[name=/Car quote/i]",
    fallbacks: ["text=/Car quote/i"],
  },
  homeQuote: {
    type: "link",
    preferred: "css=#viewSavedSubscriptionHomeQuotes",
    fallbacks: ["role=link[name=/Home quote/i]", "text=/Home quote/i"],
  },
  homeQuote2: {
    type: "button",
    preferred: "role=button[name=/Home quote/i]",
    fallbacks: ["text=/Home quote/i"],
  },
  letUsKnow: {
    type: "link",
    preferred: "css=#renewal-date-capture-link",
    fallbacks: ["role=link[name=/Let us know/i]", "text=/Let us know/i"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;