// src/pages/motor/ph-personal-details/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ph-personal-details
// scannedAt: 2026-03-09T12:58:31.799Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.ph-personal-details",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/otherDetails/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/otherDetails\/[a-z0-9]+/i,
  title: "Personal details",
  titleRe: new RegExp("Personal details", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  "12Years": "12Years" as ElementKey,
  "23Years": "23Years" as ElementKey,
  back: "back" as ElementKey,
  emailAddress: "emailAddress" as ElementKey,
  lessThan1Year: "lessThan1Year" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  mobileNumber: "mobileNumber" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  no2: "no2" as ElementKey,
  no3: "no3" as ElementKey,
  pleaseChooseTheTypeOfYourEducation: "pleaseChooseTheTypeOfYourEducation" as ElementKey,
  reactSelect10Input: "reactSelect10Input" as ElementKey,
  reactSelect5Input: "reactSelect5Input" as ElementKey,
  reactSelect6Input: "reactSelect6Input" as ElementKey,
  reactSelect7Input: "reactSelect7Input" as ElementKey,
  reactSelect8Input: "reactSelect8Input" as ElementKey,
  reactSelect9Input: "reactSelect9Input" as ElementKey,
  whatSYourEmploymentStatus: "whatSYourEmploymentStatus" as ElementKey,
  whatSYourMaritalStatus: "whatSYourMaritalStatus" as ElementKey,
  yes: "yes" as ElementKey,
  yes2: "yes2" as ElementKey,
  yes3: "yes3" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;