// src/pages/motor/ph-personal-details/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ph-personal-details
// scannedAt: 2026-03-09T12:58:31.799Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  "12Years": {
    type: "radio",
    preferred: "css=#residencyTerm2",
    fallbacks: ["css=input[name=\"residencyTerm\"]", "role=textbox[name=/1 - 2 years/i]"],
  },
  "23Years": {
    type: "radio",
    preferred: "css=#residencyTerm3",
    fallbacks: ["css=input[name=\"residencyTerm\"]", "role=textbox[name=/2 - 3 years/i]"],
  },
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  emailAddress: {
    type: "input",
    preferred: "css=#email",
    fallbacks: ["css=input[placeholder=\"name@email.com\"]", "role=textbox[name=/Email address/i]"],
  },
  lessThan1Year: {
    type: "radio",
    preferred: "css=#residencyTerm1",
    fallbacks: ["css=input[name=\"residencyTerm\"]", "role=textbox[name=/Less than 1 year/i]"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  mobileNumber: {
    type: "input",
    preferred: "css=#phoneNumber",
    fallbacks: ["css=input[placeholder=\"07XXXXXXX\"]", "role=textbox[name=/Mobile number/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  no: {
    type: "radio",
    preferred: "css=#haveSecondaryOccupationfalse",
    fallbacks: ["css=input[name=\"haveSecondaryOccupation\"]", "role=textbox[name=/No/i]"],
  },
  no2: {
    type: "radio",
    preferred: "css=#ownsHomefalse",
    fallbacks: ["css=input[name=\"ownsHome\"]", "role=textbox[name=/No/i]"],
  },
  no3: {
    type: "radio",
    preferred: "css=#residenceOfUKTermfalse",
    fallbacks: ["css=input[name=\"residenceOfUKTerm\"]", "role=textbox[name=/No/i]"],
  },
  pleaseChooseTheTypeOfYourEducation: {
    type: "select",
    preferred: "css=#education",
    fallbacks: ["role=combobox[name=/Please choose the type of your education/i]"],
  },
  reactSelect10Input: {
    type: "input",
    preferred: "css=#react-select-10-input",
    fallbacks: ["role=textbox[name=/react-select-10-input/i]"],
  },
  reactSelect5Input: {
    type: "input",
    preferred: "css=#react-select-5-input",
    fallbacks: ["role=textbox[name=/react-select-5-input/i]"],
  },
  reactSelect6Input: {
    type: "input",
    preferred: "css=#react-select-6-input",
    fallbacks: ["role=textbox[name=/react-select-6-input/i]"],
  },
  reactSelect7Input: {
    type: "input",
    preferred: "css=#react-select-7-input",
    fallbacks: ["role=textbox[name=/react-select-7-input/i]"],
  },
  reactSelect8Input: {
    type: "input",
    preferred: "css=#react-select-8-input",
    fallbacks: ["role=textbox[name=/react-select-8-input/i]"],
  },
  reactSelect9Input: {
    type: "input",
    preferred: "css=#react-select-9-input",
    fallbacks: ["role=textbox[name=/react-select-9-input/i]"],
  },
  whatSYourEmploymentStatus: {
    type: "select",
    preferred: "css=#employmentStatus",
    fallbacks: ["role=combobox[name=/What's your employment status\\?/i]"],
  },
  whatSYourMaritalStatus: {
    type: "select",
    preferred: "css=#maritalStatus",
    fallbacks: ["role=combobox[name=/What's your marital status\\?/i]"],
  },
  yes: {
    type: "radio",
    preferred: "css=#haveSecondaryOccupationtrue",
    fallbacks: ["css=input[name=\"haveSecondaryOccupation\"]", "role=textbox[name=/Yes/i]"],
  },
  yes2: {
    type: "radio",
    preferred: "css=#ownsHometrue",
    fallbacks: ["css=input[name=\"ownsHome\"]", "role=textbox[name=/Yes/i]"],
  },
  yes3: {
    type: "radio",
    preferred: "css=#residenceOfUKTermtrue",
    fallbacks: ["css=input[name=\"residenceOfUKTerm\"]", "role=textbox[name=/Yes/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;