// src/pages/motor/ad-claims-and-convictions/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ad-claims-and-convictions
// scannedAt: 2026-03-09T13:11:23.711Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.ad-claims-and-convictions",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/additionalDriver1ClaimsPage/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/additionalDriver1ClaimsPage\/[a-z0-9]+/i,
  title: "Claims for additional driver",
  titleRe: new RegExp("Claims for additional driver", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  "1": "1" as ElementKey,
  "2": "2" as ElementKey,
  "3": "3" as ElementKey,
  "4": "4" as ElementKey,
  back: "back" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  month: "month" as ElementKey,
  month2: "month2" as ElementKey,
  month3: "month3" as ElementKey,
  month4: "month4" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  removeClaim: "removeClaim" as ElementKey,
  removeClaim2: "removeClaim2" as ElementKey,
  removeClaim3: "removeClaim3" as ElementKey,
  removeClaim4: "removeClaim4" as ElementKey,
  whatHappened: "whatHappened" as ElementKey,
  whatHappened2: "whatHappened2" as ElementKey,
  whatHappened3: "whatHappened3" as ElementKey,
  whatHappened4: "whatHappened4" as ElementKey,
  year: "year" as ElementKey,
  year2: "year2" as ElementKey,
  year3: "year3" as ElementKey,
  year4: "year4" as ElementKey,
  yes: "yes" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;