// src/pages/motor/ad-claims-and-convictions/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ad-claims-and-convictions
// scannedAt: 2026-03-09T13:11:23.711Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  "1": {
    type: "radio",
    preferred: "css=#additionalDriver1NumberOfClaims1",
    fallbacks: ["css=input[name=\"additionalDriver1NumberOfClaims\"]", "role=textbox[name=/1/i]"],
  },
  "2": {
    type: "radio",
    preferred: "css=#additionalDriver1NumberOfClaims2",
    fallbacks: ["css=input[name=\"additionalDriver1NumberOfClaims\"]", "role=textbox[name=/2/i]"],
  },
  "3": {
    type: "radio",
    preferred: "css=#additionalDriver1NumberOfClaims3",
    fallbacks: ["css=input[name=\"additionalDriver1NumberOfClaims\"]", "role=textbox[name=/3/i]"],
  },
  "4": {
    type: "radio",
    preferred: "css=#additionalDriver1NumberOfClaims4",
    fallbacks: ["css=input[name=\"additionalDriver1NumberOfClaims\"]", "role=textbox[name=/4\\+/i]"],
  },
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  month: {
    type: "input",
    preferred: "css=#claim_1_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  month2: {
    type: "input",
    preferred: "css=#claim_2_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  month3: {
    type: "input",
    preferred: "css=#claim_3_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  month4: {
    type: "input",
    preferred: "css=#claim_4_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  no: {
    type: "radio",
    preferred: "css=#-false",
    fallbacks: ["role=textbox[name=/No/i]"],
  },
  removeClaim: {
    type: "link",
    preferred: "role=link[name=/Remove claim/i]",
    fallbacks: ["text=/Remove claim/i"],
  },
  removeClaim2: {
    type: "link",
    preferred: "role=link[name=/Remove claim/i]",
    fallbacks: ["text=/Remove claim/i"],
  },
  removeClaim3: {
    type: "link",
    preferred: "role=link[name=/Remove claim/i]",
    fallbacks: ["text=/Remove claim/i"],
  },
  removeClaim4: {
    type: "link",
    preferred: "role=link[name=/Remove claim/i]",
    fallbacks: ["text=/Remove claim/i"],
  },
  whatHappened: {
    type: "select",
    preferred: "css=#claim_1_description",
    fallbacks: ["role=combobox[name=/What happened\\?/i]"],
  },
  whatHappened2: {
    type: "select",
    preferred: "css=#claim_2_description",
    fallbacks: ["role=combobox[name=/What happened\\?/i]"],
  },
  whatHappened3: {
    type: "select",
    preferred: "css=#claim_3_description",
    fallbacks: ["role=combobox[name=/What happened\\?/i]"],
  },
  whatHappened4: {
    type: "select",
    preferred: "css=#claim_4_description",
    fallbacks: ["role=combobox[name=/What happened\\?/i]"],
  },
  year: {
    type: "input",
    preferred: "css=#claim_1_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  year2: {
    type: "input",
    preferred: "css=#claim_2_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  year3: {
    type: "input",
    preferred: "css=#claim_3_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  year4: {
    type: "input",
    preferred: "css=#claim_4_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  yes: {
    type: "radio",
    preferred: "css=#-true",
    fallbacks: ["role=textbox[name=/Yes/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;