// src/configLayer/models/evidence/views/consoleEvidenceFields.config.ts

import type { EvidenceFieldDefinition } from "../types";
import { EVIDENCE_STATIC_FIELDS } from "../fields/evidenceStaticFields.config";
import { EVIDENCE_RUNTIME_FIELDS } from "../fields/evidenceRuntimeFields.config";

export const CONSOLE_EVIDENCE_FIELDS = {
    DATA_HEADER: [
        EVIDENCE_STATIC_FIELDS.SCENARIO_ID,
        EVIDENCE_STATIC_FIELDS.SCENARIO_NAME,
        EVIDENCE_STATIC_FIELDS.PLATFORM,
        EVIDENCE_STATIC_FIELDS.APPLICATION,
        EVIDENCE_STATIC_FIELDS.PRODUCT,
        EVIDENCE_STATIC_FIELDS.JOURNEY_START_WITH,
        EVIDENCE_STATIC_FIELDS.TOTAL_ITEMS,
    ] as EvidenceFieldDefinition[],

    DATA_DETAIL: [
        EVIDENCE_RUNTIME_FIELDS.CALCULATED_EMAIL_ID,
        EVIDENCE_RUNTIME_FIELDS.QUOTE_NUMBER,
        EVIDENCE_RUNTIME_FIELDS.OUTPUT_POLICY_NUMBER,
        EVIDENCE_STATIC_FIELDS.STATUS,
        EVIDENCE_STATIC_FIELDS.ERROR_DETAILS,
    ] as EvidenceFieldDefinition[],

    E2E_HEADER: [
        EVIDENCE_STATIC_FIELDS.SCENARIO_ID,
        EVIDENCE_STATIC_FIELDS.SCENARIO_NAME,
        EVIDENCE_STATIC_FIELDS.PLATFORM,
        EVIDENCE_STATIC_FIELDS.APPLICATION,
        EVIDENCE_STATIC_FIELDS.PRODUCT,
        EVIDENCE_STATIC_FIELDS.JOURNEY_START_WITH,
        EVIDENCE_RUNTIME_FIELDS.POLICY_NUMBER,
        EVIDENCE_RUNTIME_FIELDS.LOGIN_ID,
        EVIDENCE_STATIC_FIELDS.DESCRIPTION,
        EVIDENCE_STATIC_FIELDS.TOTAL_ITEMS,
    ] as EvidenceFieldDefinition[],

    E2E_ITEM: [
        EVIDENCE_STATIC_FIELDS.ITEM_NO,
        EVIDENCE_STATIC_FIELDS.ACTION,
        EVIDENCE_STATIC_FIELDS.TEST_CASE_REF,
        EVIDENCE_STATIC_FIELDS.STATUS,
        EVIDENCE_STATIC_FIELDS.MESSAGE,
        EVIDENCE_STATIC_FIELDS.ERROR_DETAILS,
        EVIDENCE_RUNTIME_FIELDS.CALCULATED_EMAIL_ID,
        EVIDENCE_RUNTIME_FIELDS.QUOTE_NUMBER,
        EVIDENCE_RUNTIME_FIELDS.OUTPUT_POLICY_NUMBER,
    ] as EvidenceFieldDefinition[],
} as const;
