// src/businessLayer/pageActions/actions/athena/azonline/motor/index.ts
// AUTO-GENERATED by pageActions generator

export { carDetailsAction } from "./carDetails.action";
export { phDrivingLicenceDetailsAction } from "./phDrivingLicenceDetails.action";
