// src/businessLayer/pageActions/registry/athena/azonline/common.ts
// AUTO-GENERATED by pageActions generator

import * as actions from "../../../actions/athena/azonline/common";

export const common = {
    insuranceTypeSelection: actions.insuranceTypeSelectionAction,
    loginOrRegistration: actions.loginOrRegistrationAction,
    manageCookies: actions.manageCookiesAction,
} as const;
