// src/businessLayer/pageActions/registry/athena/azonline/index.ts
// AUTO-GENERATED by pageActions generator

import { common } from "./common";
import { motor } from "./motor";

export const azonline = {
    common,
    motor,
} as const;
