// src/businessLayer/pageActions/registry/athena/azonline/motor.ts
// AUTO-GENERATED by pageActions generator

import * as actions from "../../../actions/athena/azonline/motor";

export const motor = {
    carDetails: actions.carDetailsAction,
    phDrivingLicenceDetails: actions.phDrivingLicenceDetailsAction,
} as const;
