// src/toolingLayer/pageActions/generator/core/registry/ensurePageActionIndexes.ts

import fs from "node:fs";
import path from "node:path";
import { toRepoRelative } from "@utils/paths";
import type { ActionRegistryEntry } from "../../shared/types";

type RegistryWriteResult = {
    createdFiles: number;
    updatedFiles: number;
};

function ensureTrailingNewline(text: string): string {
    return text.endsWith("\n") ? text : `${text}\n`;
}

function withHeader(filePath: string, body: string): string {
    return [
        `// ${toRepoRelative(filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        body.trimEnd(),
        ``,
    ].join("\n");
}

function writeIfChanged(
    filePath: string,
    body: string
): { created: boolean; updated: boolean } {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });

    const next = ensureTrailingNewline(withHeader(filePath, body));
    const exists = fs.existsSync(filePath);
    const current = exists ? fs.readFileSync(filePath, "utf8") : "";

    if (current === next) {
        return { created: false, updated: false };
    }

    fs.writeFileSync(filePath, next, "utf8");

    return {
        created: !exists,
        updated: exists,
    };
}

function buildRootIndex(): string {
    return [
        `export * from "./shared";`,
        `export * from "./actions";`,
        ``,
    ].join("\n");
}

function buildActionsIndex(platforms: string[]): string {
    return [
        ...platforms.map((platform) => `export * from "./${platform}";`),
        ``,
    ].join("\n");
}

function buildPlatformIndex(applications: string[]): string {
    return [
        ...applications.map(
            (application) => `export * from "./${application}";`
        ),
        ``,
    ].join("\n");
}

function buildApplicationIndex(products: string[]): string {
    return [
        ...products.map((product) => `export * from "./${product}";`),
        ``,
    ].join("\n");
}

function buildProductIndex(entries: ActionRegistryEntry[]): string {
    const lines = entries
        .slice()
        .sort((a, b) => a.pageKey.localeCompare(b.pageKey))
        .map((entry) => {
            const importPath = `./${entry.actionFileName.replace(".ts", "")}`;
            return `export { ${entry.actionName} } from "${importPath}";`;
        });

    return [...lines, ``].join("\n");
}

function applyWriteResult(
    totals: RegistryWriteResult,
    result: { created: boolean; updated: boolean }
): void {
    if (result.created) {
        totals.createdFiles++;
    }

    if (result.updated) {
        totals.updatedFiles++;
    }
}

export function ensurePageActionIndexes(args: {
    entries: ActionRegistryEntry[];
}): RegistryWriteResult {
    const { entries } = args;
    const totals: RegistryWriteResult = {
        createdFiles: 0,
        updatedFiles: 0,
    };

    if (entries.length === 0) {
        return totals;
    }

    const rootIndexFile = entries[0].paths.rootIndexFile;
    const actionsIndexFile = entries[0].paths.actionsIndexFile;

    applyWriteResult(totals, writeIfChanged(rootIndexFile, buildRootIndex()));

    const platforms = [...new Set(entries.map((entry) => entry.scope.platform))]
        .sort((a, b) => a.localeCompare(b));

    applyWriteResult(
        totals,
        writeIfChanged(actionsIndexFile, buildActionsIndex(platforms))
    );

    for (const platform of platforms) {
        const platformEntries = entries.filter(
            (entry) => entry.scope.platform === platform
        );
        const platformIndexFile = platformEntries[0].paths.platformIndexFile;
        const applications = [
            ...new Set(platformEntries.map((entry) => entry.scope.application)),
        ].sort((a, b) => a.localeCompare(b));

        applyWriteResult(
            totals,
            writeIfChanged(platformIndexFile, buildPlatformIndex(applications))
        );

        for (const application of applications) {
            const applicationEntries = platformEntries.filter(
                (entry) => entry.scope.application === application
            );
            const applicationIndexFile =
                applicationEntries[0].paths.applicationIndexFile;
            const products = [
                ...new Set(applicationEntries.map((entry) => entry.scope.product)),
            ].sort((a, b) => a.localeCompare(b));

            applyWriteResult(
                totals,
                writeIfChanged(
                    applicationIndexFile,
                    buildApplicationIndex(products)
                )
            );

            for (const product of products) {
                const productEntries = applicationEntries.filter(
                    (entry) => entry.scope.product === product
                );
                const productIndexFile = productEntries[0].paths.productIndexFile;

                applyWriteResult(
                    totals,
                    writeIfChanged(
                        productIndexFile,
                        buildProductIndex(productEntries)
                    )
                );
            }
        }
    }

    return totals;
}
