// src/pages/motor/cover-start-date/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.cover-start-date
// scannedAt: 2026-03-09T13:13:21.956Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.cover-start-date",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/coverOptions/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/coverOptions\/[a-z0-9]+/i,
  title: "Start date",
  titleRe: new RegExp("Start date", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  back: "back" as ElementKey,
  getAQuote: "getAQuote" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  nextMonth: "nextMonth" as ElementKey,
  pleaseSelectDate: "pleaseSelectDate" as ElementKey,
  selectDate: "selectDate" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;