// src/pages/motor/cover-start-date/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.cover-start-date
// scannedAt: 2026-03-09T13:13:21.956Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  getAQuote: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Get a quote/i]", "text=/Get a quote/i"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  nextMonth: {
    type: "button",
    preferred: "css=button[aria-label=\"Next Month\"]",
    fallbacks: ["role=button[name=/Next Month/i]", "text=/Next Month/i"],
  },
  pleaseSelectDate: {
    type: "radio",
    preferred: "css=#datePickerCalendar",
    fallbacks: ["css=input[name=\"date\"]", "role=dialog[name=/Please select date/i]"],
  },
  selectDate: {
    type: "button",
    preferred: "css=#set-date",
    fallbacks: ["role=button[name=/Select date/i]", "text=/Select date/i"],
  },
} as const;

export type ElementKey = keyof typeof elements;