// src/pages/objects/athena/common/login-or-registration/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: athena.common.login-or-registration
// scannedAt: 2026-03-09T12:48:41.552Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  logIn: {
    type: "link",
    preferred: "css=#login",
    fallbacks: ["role=link[name=/Log in/i]", "text=/Log in/i"],
  },
  register: {
    type: "link",
    preferred: "css=#register",
    fallbacks: ["role=link[name=/Register/i]", "text=/Register/i"],
  },
  skipThisStepILlRegisterLater: {
    type: "link",
    preferred: "css=#skipRegistration",
    fallbacks: ["role=link[name=/Skip this step, I’ll register later/i]", "text=/Skip this step, I’ll register later/i"],
  },
} as const;

export type ElementKey = keyof typeof elements;