// src/pages/motor/car-details/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.car-details
// scannedAt: 2026-03-09T12:52:20.271Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.car-details",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/numberPlateScan/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/numberPlateScan\/[a-z0-9]+/i,
  title: "Car details",
  titleRe: new RegExp("Car details", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  allDone: "allDone" as ElementKey,
  automatic: "automatic" as ElementKey,
  back: "back" as ElementKey,
  diesel: "diesel" as ElementKey,
  findMyCar: "findMyCar" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  manual: "manual" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  no2: "no2" as ElementKey,
  petrol: "petrol" as ElementKey,
  purchaseMonthInputField: "purchaseMonthInputField" as ElementKey,
  purchaseYearInputField: "purchaseYearInputField" as ElementKey,
  startTypingTheMakeOfYourVehicle: "startTypingTheMakeOfYourVehicle" as ElementKey,
  startTypingTheModelNameOfYourVehicle: "startTypingTheModelNameOfYourVehicle" as ElementKey,
  startTypingTheModelNameOfYourVehicle2: "startTypingTheModelNameOfYourVehicle2" as ElementKey,
  theCarHasnTBeenBoughtYet: "theCarHasnTBeenBoughtYet" as ElementKey,
  uploadAPhotoOfYourCarSNumberPlate: "uploadAPhotoOfYourCarSNumberPlate" as ElementKey,
  vehicleDoors: "vehicleDoors" as ElementKey,
  vehicleManufactureYear: "vehicleManufactureYear" as ElementKey,
  viewHowWeLlUseYourInfo: "viewHowWeLlUseYourInfo" as ElementKey,
  whatSYourCarRegistrationNumber: "whatSYourCarRegistrationNumber" as ElementKey,
  yes: "yes" as ElementKey,
  yes2: "yes2" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;