// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.car-details
// scannedAt: 2026-03-01T09:43:18.087Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.car-details",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/numberPlateScan/69a409b5d35138197f847674",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/numberPlateScan\/[a-z0-9]+/i,
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  allDone: "allDone" as ElementKey,
  back: "back" as ElementKey,
  findMyCar: "findMyCar" as ElementKey,
  hasmodificationFalseNo: "hasmodificationFalseNo" as ElementKey,
  hasmodificationTrueYes: "hasmodificationTrueYes" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  next: "next" as ElementKey,
  purchaseMonthInputField: "purchaseMonthInputField" as ElementKey,
  purchaseYearInputField: "purchaseYearInputField" as ElementKey,
  registrationnumberpolarquestionNo: "registrationnumberpolarquestionNo" as ElementKey,
  registrationnumberpolarquestionYes: "registrationnumberpolarquestionYes" as ElementKey,
  startTypingTheMakeOfYourVehicle: "startTypingTheMakeOfYourVehicle" as ElementKey,
  startTypingTheModelNameOfYourVehicle: "startTypingTheModelNameOfYourVehicle" as ElementKey,
  startTypingTheModelNameOfYourVehicle2: "startTypingTheModelNameOfYourVehicle2" as ElementKey,
  theCarHasnTBeenBoughtYet: "theCarHasnTBeenBoughtYet" as ElementKey,
  uploadAPhotoOfYourCarSNumberPlate: "uploadAPhotoOfYourCarSNumberPlate" as ElementKey,
  vehicledetailssetcorrectlyNo: "vehicledetailssetcorrectlyNo" as ElementKey,
  vehicledetailssetcorrectlyYes: "vehicledetailssetcorrectlyYes" as ElementKey,
  vehicleDoors: "vehicleDoors" as ElementKey,
  vehiclefueltypedDiesel: "vehiclefueltypedDiesel" as ElementKey,
  vehiclefueltypepPetrol: "vehiclefueltypepPetrol" as ElementKey,
  vehicleManufactureYear: "vehicleManufactureYear" as ElementKey,
  vehicletransmissionaAutomatic: "vehicletransmissionaAutomatic" as ElementKey,
  vehicletransmissionmManual: "vehicletransmissionmManual" as ElementKey,
  viewHowWeLlUseYourInfo: "viewHowWeLlUseYourInfo" as ElementKey,
  whatSYourCarRegistrationNumber: "whatSYourCarRegistrationNumber" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;