// AUTO-GENERATED by src/scanner/generateElements.ts
// pageKey: motor.car-details
// scannedAt: 2026-03-01T09:43:18.087Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  allDone: {
    type: "button",
    preferred: "role=button[name=/All done/i]",
    fallbacks: ["text=/All done/i"],
  },
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  findMyCar: {
    type: "button",
    preferred: "role=button[name=/Find my car/i]",
    fallbacks: ["text=/Find my car/i"],
  },
  hasmodificationFalseNo: {
    type: "radio",
    preferred: "css=#hasModificationsfalse",
    fallbacks: ["css=input[name=\"hasModification-false\"]", "role=textbox[name=/No/i]"],
  },
  hasmodificationTrueYes: {
    type: "radio",
    preferred: "css=#hasModificationstrue",
    fallbacks: ["css=input[name=\"hasModification-true\"]", "role=textbox[name=/Yes/i]"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  purchaseMonthInputField: {
    type: "input",
    preferred: "css=#purchase-date-month",
    fallbacks: ["css=input[aria-label=\"Purchase month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Purchase month input field/i]"],
  },
  purchaseYearInputField: {
    type: "input",
    preferred: "css=#purchase-date-year",
    fallbacks: ["css=input[aria-label=\"Purchase year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Purchase year input field/i]"],
  },
  registrationnumberpolarquestionNo: {
    type: "radio",
    preferred: "css=#registrationNumberPolarQuestiontrue",
    fallbacks: ["css=input[name=\"registrationNumberPolarQuestion\"]", "role=textbox[name=/No/i]"],
  },
  registrationnumberpolarquestionYes: {
    type: "radio",
    preferred: "css=#registrationNumberPolarQuestionfalse",
    fallbacks: ["css=input[name=\"registrationNumberPolarQuestion\"]", "role=textbox[name=/Yes/i]"],
  },
  startTypingTheMakeOfYourVehicle: {
    type: "input",
    preferred: "css=#vehicle-make",
    fallbacks: ["css=input[placeholder=\"Start typing the make of your vehicle...\"]", "role=textbox[name=/Start typing the make of your vehicle\\.\\.\\./i]"],
  },
  startTypingTheModelNameOfYourVehicle: {
    type: "input",
    preferred: "css=#vehicle-shortened-model",
    fallbacks: ["css=input[placeholder=\"Start typing the model name of your vehicle...\"]", "role=textbox[name=/Start typing the model name of your vehicle\\.\\.\\./i]"],
  },
  startTypingTheModelNameOfYourVehicle2: {
    type: "input",
    preferred: "css=#vehicle-model",
    fallbacks: ["css=input[placeholder=\"Start typing the model name of your vehicle...\"]", "role=textbox[name=/Start typing the model name of your vehicle\\.\\.\\./i]"],
  },
  theCarHasnTBeenBoughtYet: {
    type: "checkbox",
    preferred: "css=#notBeenBoughtCheckbox",
    fallbacks: ["css=input[aria-label=\"The car hasn't been bought yet\"]", "role=textbox[name=/The car hasn't been bought yet/i]"],
  },
  uploadAPhotoOfYourCarSNumberPlate: {
    type: "input",
    preferred: "css=#vrn-widget-upload-input",
    fallbacks: ["role=textbox[name=/upload a photo of your car's number plate/i]"],
  },
  vehicledetailssetcorrectlyNo: {
    type: "radio",
    preferred: "css=#vehicleDetailsSetCorrectly-false",
    fallbacks: ["css=input[name=\"vehicleDetailsSetCorrectly\"]", "role=textbox[name=/No/i]"],
  },
  vehicledetailssetcorrectlyYes: {
    type: "radio",
    preferred: "css=#vehicleDetailsSetCorrectly-true",
    fallbacks: ["css=input[name=\"vehicleDetailsSetCorrectly\"]", "role=textbox[name=/Yes/i]"],
  },
  vehicleDoors: {
    type: "select",
    preferred: "css=#vehicle-doors",
    fallbacks: ["role=combobox[name=/vehicle-doors/i]"],
  },
  vehiclefueltypedDiesel: {
    type: "radio",
    preferred: "css=#vehicleFuelTypeD",
    fallbacks: ["css=input[name=\"vehicleFuelTypeD\"]", "role=textbox[name=/Diesel/i]"],
  },
  vehiclefueltypepPetrol: {
    type: "radio",
    preferred: "css=#vehicleFuelTypeP",
    fallbacks: ["css=input[name=\"vehicleFuelTypeP\"]", "role=textbox[name=/Petrol/i]"],
  },
  vehicleManufactureYear: {
    type: "select",
    preferred: "css=#vehicle-manufacture-year",
    fallbacks: ["role=combobox[name=/vehicle-manufacture-year/i]"],
  },
  vehicletransmissionaAutomatic: {
    type: "radio",
    preferred: "css=#vehicleTransmissionA",
    fallbacks: ["css=input[name=\"vehicleTransmissionA\"]", "role=textbox[name=/Automatic/i]"],
  },
  vehicletransmissionmManual: {
    type: "radio",
    preferred: "css=#vehicleTransmissionM",
    fallbacks: ["css=input[name=\"vehicleTransmissionM\"]", "role=textbox[name=/Manual/i]"],
  },
  viewHowWeLlUseYourInfo: {
    type: "link",
    preferred: "css=#personal-info-use",
    fallbacks: ["role=link[name=/view how we’ll use your info/i]", "text=/view how we’ll use your info/i"],
  },
  whatSYourCarRegistrationNumber: {
    type: "input",
    preferred: "css=#registrationNumber",
    fallbacks: ["role=textbox[name=/What’s your car registration number\\?/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;
