// src/reporters/dashboard/dashboardConfig.ts

export type DashboardUiConfig = {
    header: {
        title: string;          // e.g. "AZOnline – Playwright Dashboard"
        subtitle?: string;      // e.g. "Smoke + Regression"
        rightBadge?: string;    // e.g. "chromium"
    };
    footer: {
        leftText?: string;      // e.g. "Team QA – AZOnline"
        links?: Array<{ label: string; href: string }>; // rendered as anchors
    };
};

export const dashboardUiConfig: DashboardUiConfig = {
    header: {
        title: "Playwright Test Dashboard",
        subtitle: "Local run / CI run",
        rightBadge: "AZOnline",
    },
    footer: {
        leftText: "Generated by reporters/dashboard",
        links: [
            { label: "Playwright HTML report", href: "../html/index.html" },
        ],
    },
};