// src/businessLayer/pageActions/actions/athena/azonline/common/index.ts
// AUTO-GENERATED by pageActions generator

export { insuranceTypeSelectionAction } from "./insuranceTypeSelection.action";
export { loginOrRegistrationAction } from "./loginOrRegistration.action";
export { manageCookiesAction } from "./manageCookies.action";
