// src/tools/page-object-generator/builders/buildAliasesGeneratedTs.ts

import type { PageMap } from "../generator/types";
import { buildUrlReFromUrlPath } from "../generator/urlMeta";

import { isValidTsIdentifier } from "../../../utils/ts";
import { escapeForRegex } from "../../../utils/regex";

function buildSafeUrlRe(urlPath: string): string | undefined {
    const clean = urlPath.trim();
    if (!clean) return undefined;

    // Prefer shared helper
    const fromHelper = buildUrlReFromUrlPath(clean);
    if (fromHelper) {
        return fromHelper;
    }

    // Fallback: exact path match, including "/"
    return `new RegExp("^${escapeForRegex(clean)}$", "i")`;
}

export function buildAliasesGeneratedTs(pageMap: PageMap): string {
    const lines: string[] = [];

    const scannedAt = pageMap.scannedAt ?? new Date().toISOString();

    // title is optional (newer scanner versions)
    const title =
        typeof (pageMap as any).title === "string" && (pageMap as any).title.trim()
            ? String((pageMap as any).title).trim()
            : undefined;

    lines.push(`// src/pages/objects/${pageMap.pageKey.split(".").join("/")}/aliases.generated.ts`);
    lines.push(`// AUTO-GENERATED by src/scanner/elements-generator`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`// scannedAt: ${scannedAt}`);
    lines.push(``);
    lines.push(`import type { ElementKey } from "./elements";`);
    lines.push(``);
    lines.push(`// Page metadata (used for waitForURL / assertions)`);
    lines.push(`export const pageMeta = {`);
    lines.push(`  pageKey: ${JSON.stringify(pageMap.pageKey)},`);

    if (typeof pageMap.urlPath === "string" && pageMap.urlPath.trim()) {
        const cleanUrlPath = pageMap.urlPath.trim();
        const urlReLiteral = buildSafeUrlRe(cleanUrlPath);

        lines.push(`  urlPath: ${JSON.stringify(cleanUrlPath)},`);
        if (urlReLiteral) {
            lines.push(`  urlRe: ${urlReLiteral},`);
        }
    }

    // title support (optional)
    if (title) {
        lines.push(`  title: ${JSON.stringify(title)},`);
        lines.push(
            `  titleRe: new RegExp(${JSON.stringify(escapeForRegex(title))}, "i"),`
        );
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`// Default alias mapping: alias key == element key`);
    lines.push(`export const aliasesGenerated = {`);

    const keys = Object.keys(pageMap.elements).sort((a, b) => a.localeCompare(b));
    for (const k of keys) {
        const prop = isValidTsIdentifier(k) ? k : JSON.stringify(k);
        lines.push(`  ${prop}: ${JSON.stringify(k)} as ElementKey,`);
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type AliasGeneratedKey = keyof typeof aliasesGenerated;`);

    return lines.join("\n");
}