// src/tools/page-object-generator/builders/buildElementsTs.ts

import type { PageMap, PageMapElement } from "../generator/types";
import { escapeTsString, isValidTsIdentifier } from "../../../utils/ts";

type ElementEntry = {
    key: string;
    value: PageMapElement;
};

function prop(key: string): string {
    return isValidTsIdentifier(key) ? key : JSON.stringify(key);
}

function renderEntry(entry: ElementEntry): string[] {
    const { key, value } = entry;
    const fallbacks = Array.isArray(value.fallbacks) ? value.fallbacks : [];
    const items = fallbacks.map((f) => `"${escapeTsString(f)}"`).join(", ");
    const lines: string[] = [];

    lines.push(`  ${prop(key)}: {`);
    lines.push(`    type: "${escapeTsString(value.type)}",`);
    lines.push(`    preferred: "${escapeTsString(value.preferred)}",`);
    lines.push(`    fallbacks: [${items}],`);

    if (value.stableKey) {
        lines.push(`    stableKey: "${escapeTsString(value.stableKey)}",`);
    }

    lines.push(`  },`);
    return lines;
}

export function buildElementsTs(pageMap: PageMap): string {
    const entries = Object.entries(pageMap.elements).map(([key, value]) => ({ key, value }));
    const lines: string[] = [];

    lines.push(`// src/pages/objects/${pageMap.pageKey.split(".").join("/")}/elements.ts`);
    lines.push(`// AUTO-GENERATED by src/scanner/elements-generator`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`// scannedAt: ${pageMap.scannedAt ?? new Date().toISOString()}`);
    lines.push(``);
    lines.push(`export type ElementDef = {`);
    lines.push(`  type: string;`);
    lines.push(`  preferred: string;`);
    lines.push(`  fallbacks: readonly string[];`);
    lines.push(`  stableKey?: string;`);
    lines.push(`};`);
    lines.push(``);
    lines.push(`export const elements = {`);

    for (const entry of entries) {
        lines.push(...renderEntry(entry));
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type ElementKey = keyof typeof elements;`);

    return lines.join("\n");
}