// src/pages/objects/athena/common/insurance-type-selection/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: athena.common.insurance-type-selection
// scannedAt: 2026-03-13T10:57:20.737Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  buttonInputBack: {
    type: "button",
    preferred: "role=button[name=/Back/i]",
    fallbacks: ["text=/Back/i"],
  },
  linkCarQuote: {
    type: "link",
    preferred: "css=#viewSavedSubscriptionCarQuotes",
    fallbacks: ["role=link[name=/Car quote/i]", "text=/Car quote/i"],
  },
  linkHomeQuote: {
    type: "link",
    preferred: "css=#viewSavedSubscriptionHomeQuotes",
    fallbacks: ["role=link[name=/Home quote/i]", "text=/Home quote/i"],
  },
  linkInputBack: {
    type: "link",
    preferred: "role=link[name=/Back/i]",
    fallbacks: ["text=/Back/i"],
  },
  linkLetUsKnow: {
    type: "link",
    preferred: "css=#renewal-date-capture-link",
    fallbacks: ["role=link[name=/Let us know/i]", "text=/Let us know/i"],
  },
  linkTermsAndConditionsApply: {
    type: "link",
    preferred: "role=link[name=/T&Cs apply/i]",
    fallbacks: ["text=/T&Cs apply/i"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;