// src/scanner/elements-generator/builders/buildAliasesGeneratedTs.ts

import type { PageMap } from "../generator/types";
import { buildUrlReFromUrlPath } from "../generator/urlMeta";

function isValidTsIdentifier(key: string) {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

function escapeRegExp(s: string) {
    // escape for RegExp constructor
    return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function buildAliasesGeneratedTs(pageMap: PageMap): string {
    const lines: string[] = [];

    const scannedAt = pageMap.scannedAt ?? new Date().toISOString();

    // title is optional (newer scanner versions)
    const title =
        typeof (pageMap as any).title === "string" && (pageMap as any).title.trim()
            ? String((pageMap as any).title).trim()
            : undefined;

    lines.push(`// AUTO-GENERATED by src/scanner/elements-generator`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`// scannedAt: ${scannedAt}`);
    lines.push(``);
    lines.push(`import type { ElementKey } from "./elements";`);
    lines.push(``);
    lines.push(`// Page metadata (used for waitForURL / assertions)`);
    lines.push(`export const pageMeta = {`);
    lines.push(`  pageKey: ${JSON.stringify(pageMap.pageKey)},`);

    if (pageMap.urlPath) {
        const urlReLiteral = buildUrlReFromUrlPath(pageMap.urlPath);
        lines.push(`  urlPath: ${JSON.stringify(pageMap.urlPath)},`);
        if (urlReLiteral) {
            // urlReLiteral is already a TS regex literal string like: /\/...\/[a-z0-9]+/i
            lines.push(`  urlRe: ${urlReLiteral},`);
        }
    }

    // ✅ NEW: title support (optional)
    if (title) {
        lines.push(`  title: ${JSON.stringify(title)},`);
        // Keep a "loose" matcher for convenience (case-insensitive contains)
        lines.push(
            `  titleRe: new RegExp(${JSON.stringify(escapeRegExp(title))}, "i"),`
        );
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`// Default alias mapping: alias key == element key`);
    lines.push(`export const aliasesGenerated = {`);

    const keys = Object.keys(pageMap.elements).sort((a, b) => a.localeCompare(b));
    for (const k of keys) {
        const prop = isValidTsIdentifier(k) ? k : JSON.stringify(k);
        lines.push(`  ${prop}: ${JSON.stringify(k)} as ElementKey,`);
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type AliasGeneratedKey = keyof typeof aliasesGenerated;`);

    return lines.join("\n");
}