// src/tools/page-elements-generator/builders/buildElementsTs.ts

import type { PageMap } from "../generator/types";
import { escapeTsString, isValidTsIdentifier } from "../../../utils/ts";

export function buildElementsTs(pageMap: PageMap): string {
    
    const lines: string[] = [];

    lines.push(`// src/pages/${pageMap.pageKey.split(".").join("/")}/elements.ts`);
    lines.push(`// AUTO-GENERATED by src/scanner/elements-generator`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`// scannedAt: ${pageMap.scannedAt ?? new Date().toISOString()}`);
    lines.push(``);
    lines.push(`export type ElementDef = {`);
    lines.push(`  type: string;`);
    lines.push(`  preferred: string;`);
    lines.push(`  fallbacks: readonly string[];`);
    lines.push(`};`);
    lines.push(``);
    lines.push(`export const elements = {`);

    // Stable order (nice diffs)
    const entries = Object.entries(pageMap.elements).sort(([a], [b]) => a.localeCompare(b));

    for (const [key, v] of entries) {
        const prop = isValidTsIdentifier(key) ? key : JSON.stringify(key);

        lines.push(`  ${prop}: {`);
        lines.push(`    type: "${escapeTsString(v.type)}",`);
        lines.push(`    preferred: "${escapeTsString(v.preferred)}",`);

        const fallbacks = Array.isArray(v.fallbacks) ? v.fallbacks : [];
        if (fallbacks.length) {
            const items = fallbacks.map((f) => `"${escapeTsString(f)}"`).join(", ");
            lines.push(`    fallbacks: [${items}],`);
        } else {
            lines.push(`    fallbacks: [],`);
        }

        lines.push(`  },`);
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type ElementKey = keyof typeof elements;`);

    return lines.join("\n");
}