// src/tools/page-elements-generator/builders/buildPageTsStub.ts

import type { PageMap } from "../generator/types";
import { toPascal } from "../../../utils/ts";

export function buildPageTsStub(pageMap: PageMap): string {
    const pageKey = pageMap.pageKey;
    const lastSeg = pageKey.split(".").slice(-1)[0] || "page";
    const className = `${toPascal(lastSeg)}Page`;

    const lines: string[] = [];

    lines.push(`// AUTO-SCAFFOLDED (create-only) by src/scanner/elements-generator`);
    lines.push(`// pageKey: ${pageKey}`);
    lines.push(``);
    lines.push(`import type { Page } from "@playwright/test";`);
    lines.push(`import { expect } from "@playwright/test";`);
    lines.push(`import { BasePage } from "../../core/BasePage"; // adjust if needed`);
    lines.push(`import { elements } from "./elements";`);
    lines.push(`import { aliases } from "./aliases";`);
    lines.push(`import { pageMeta } from "./aliases.generated";`);
    lines.push(`import type { AliasKey } from "./aliases";`);
    lines.push(``);
    lines.push(`const PAGE_KEY = ${JSON.stringify(pageKey)} as const;`);
    lines.push(``);
    lines.push(`export class ${className} extends BasePage {`);
    lines.push(`  constructor(page: Page) {`);
    lines.push(`    super(page);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  // --------------------------------------------------`);
    lines.push(`  // Page-level helpers (URL + Title awareness)`);
    lines.push(`  // --------------------------------------------------`);
    lines.push(``);
    lines.push(`  async waitForPage() {`);
    lines.push(`    const timeout = Number(process.env.PAGE_TIMEOUT ?? 15_000);`);
    lines.push(``);
    lines.push(`    if (pageMeta.urlRe) {`);
    lines.push(`      await this.page.waitForURL(pageMeta.urlRe, { timeout });`);
    lines.push(`    } else if (pageMeta.urlPath) {`);
    lines.push(`      await this.page.waitForURL(new RegExp(pageMeta.urlPath), { timeout });`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    if ((pageMeta as any).titleRe) {`);
    lines.push(`      await expect(this.page).toHaveTitle((pageMeta as any).titleRe, { timeout });`);
    lines.push(`    } else if ((pageMeta as any).title) {`);
    lines.push(`      await expect(this.page).toHaveTitle((pageMeta as any).title, { timeout });`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  async assertOnPage() {`);
    lines.push(`    if (pageMeta.urlRe) {`);
    lines.push(`      await expect(this.page).toHaveURL(pageMeta.urlRe);`);
    lines.push(`    } else if (pageMeta.urlPath) {`);
    lines.push(`      await expect(this.page).toHaveURL(new RegExp(pageMeta.urlPath));`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    if ((pageMeta as any).titleRe) {`);
    lines.push(`      await expect(this.page).toHaveTitle((pageMeta as any).titleRe);`);
    lines.push(`    } else if ((pageMeta as any).title) {`);
    lines.push(`      await expect(this.page).toHaveTitle((pageMeta as any).title);`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  // --------------------------------------------------`);
    lines.push(`  // Alias wrappers (so generated methods stay simple)`);
    lines.push(`  // --------------------------------------------------`);
    lines.push(``);
    lines.push(`  protected async clickAlias(aliasKey: AliasKey) {`);
    lines.push(`    await this.clickByAlias(PAGE_KEY, aliases, elements, aliasKey);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  protected async fillAlias(aliasKey: AliasKey, value: string) {`);
    lines.push(`    await this.fillByAlias(PAGE_KEY, aliases, elements, aliasKey, value);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  protected async selectOptionAlias(aliasKey: AliasKey, value: string) {`);
    lines.push(`    await this.selectOptionByAlias(PAGE_KEY, aliases, elements, aliasKey, value);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  protected async setCheckedAlias(aliasKey: AliasKey, checked: boolean = true) {`);
    lines.push(`    const { locator } = await this.resolveByAlias(PAGE_KEY, aliases, elements, aliasKey);`);
    lines.push(`    await locator.setChecked(checked, { timeout: Number(process.env.ACTION_TIMEOUT ?? 10_000) });`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  // <scanner:aliases>`);
    lines.push(`  // This region is auto-managed. Do not edit by hand.`);
    lines.push(`  // </scanner:aliases>`);
    lines.push(``);
    lines.push(`  // You can add custom business logic methods below (safe zone).`);
    lines.push(`}`);
    lines.push(``);

    return lines.join("\n");
}