// src/toolingLayer/pageActions/common/runtimeRegistry/buildRegistryLeafContent.ts

import path from "node:path";
import { toRepoRelative } from "@utils/paths";
import type { ActionRuntimeRegistryEntry } from "../../generator/shared/types";
import { toCamelCase } from "../../generator/shared/naming";

export function buildRegistryLeafContent(args: {
    filePath: string;
    objectName: string;
    entries: ActionRuntimeRegistryEntry[];
    actionIndexFile: string;
}): string {
    const importPath = path
        .relative(path.dirname(args.filePath), args.actionIndexFile)
        .replace(/\\/g, "/")
        .replace(/\/index\.ts$/, "")
        .replace(/\.ts$/, "");

    const lines = args.entries
        .slice()
        .sort((a, b) => a.pageKey.localeCompare(b.pageKey))
        .map((entry) => {
            const memberName = toCamelCase(entry.scope.name);
            return `    ${memberName}: actions.${entry.actionName},`;
        });

    return [
        `// ${toRepoRelative(args.filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        `import * as actions from "${importPath}";`,
        ``,
        `export const ${args.objectName} = {`,
        ...lines,
        `} as const;`,
        ``,
    ].join("\n");
}
