// src/toolingLayer/pageActions/common/runtimeRegistry/buildRegistryBranchContent.ts

import { toRepoRelative } from "@utils/paths";

export function buildRegistryBranchContent(args: {
    filePath: string;
    objectName: string;
    childNames: string[];
}): string {
    const imports = args.childNames.map(
        (childName) => `import { ${childName} } from "./${childName}";`
    );
    const members = args.childNames.map(
        (childName) => `    ${childName},`
    );

    return [
        `// ${toRepoRelative(args.filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        ...imports,
        ``,
        `export const ${args.objectName} = {`,
        ...members,
        `} as const;`,
        ``,
    ].join("\n");
}
