// src/toolingLayer/pageActions/common/runtimeRegistry/buildRuntimeRegistryContent.ts

import { toRepoRelative } from "@utils/paths";

export function buildRuntimeRegistryContent(args: {
    filePath: string;
    platformNames: string[];
}): string {
    const imports = args.platformNames.map(
        (platformName) => `import { ${platformName} } from "./${platformName}";`
    );
    const members = args.platformNames.map(
        (platformName) => `    ${platformName},`
    );

    return [
        `// ${toRepoRelative(args.filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        ...imports,
        ``,
        `export const pageActionsRegistry = {`,
        ...members,
        `} as const;`,
        ``,
    ].join("\n");
}
