// src/toolingLayer/pageActions/common/runtimeRegistry/buildRuntimeRegistryIndexContent.ts

import { toRepoRelative } from "@utils/paths";

export function buildRuntimeRegistryIndexContent(
    filePath: string
): string {
    return [
        `// ${toRepoRelative(filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        `export * from "./pageActionsRegistry";`,
        ``,
    ].join("\n");
}
