// src/tools/pageObjects/generator/utils/buildGeneratedHeader.ts

import path from "node:path";
import {
    PAGE_OBJECTS_ROOT_DIR,
    toRepoRelative,
} from "@utils/paths";

/**
 * Build repo-relative file path for page object artifacts
 */
function buildPageObjectPath(parts: string[]): string {
    return toRepoRelative(path.join(PAGE_OBJECTS_ROOT_DIR, ...parts));
}

/**
 * Header line: file path comment
 */
export function headerFilePath(parts: string[]): string {
    return `// ${buildPageObjectPath(parts)}`;
}

/**
 * Header line: auto-generated comment
 */
export function headerGeneratedBy(source: string): string {
    return `// AUTO-GENERATED by ${source}`;
}

/**
 * Header line: scaffold comment
 */
export function headerScaffoldedBy(source: string): string {
    return `// AUTO-SCAFFOLDED (create-only) by ${source}`;
}

/**
 * Header line: manifest comment
 */
export function headerGeneratedFromManifest(): string {
    const manifestPath = buildPageObjectPath([".manifest"]);
    return `// AUTO-GENERATED from ${manifestPath}/`;
}

/**
 * Helpers for common pageObject artifacts
 */
export function getPageObjectFileParts(pageKey: string, fileName: string): string[] {
    return ["objects", ...pageKey.split("."), fileName];
}

export function getPageManagerFileParts(): string[] {
    return ["pageManager.ts"];
}

export function getIndexFileParts(): string[] {
    return ["index.ts"];
}