// src/pages/motor/ad-driving-licence-details/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ad-driving-licence-details
// scannedAt: 2026-03-09T13:08:06.096Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  addFrontOfLicence: {
    type: "button",
    preferred: "css=#dl-widget-upload-input-front",
    fallbacks: ["role=button[name=/Add front of licence/i]"],
  },
  addFrontOfLicence2: {
    type: "button",
    preferred: "css=label[aria-label=\"Add front of license\"]",
    fallbacks: ["role=button[name=/Add front of license/i]"],
  },
  additionaldriver1partialdrivinglicencenumberquestionmonthpart: {
    type: "input",
    preferred: "css=#additionalDriver1PartialDrivingLicenceNumberQuestionmonthPart",
    fallbacks: ["role=textbox[name=/additionalDriver1PartialDrivingLicenceNumberQuestionmonthPart/i]"],
  },
  additionaldriver1partialdrivinglicencenumberquestionrandompart: {
    type: "input",
    preferred: "css=#additionalDriver1PartialDrivingLicenceNumberQuestionrandomPart",
    fallbacks: ["role=textbox[name=/additionalDriver1PartialDrivingLicenceNumberQuestionrandomPart/i]"],
  },
  addresslookupwidgetAddresslookupquestioninputBuilding: {
    type: "input",
    preferred: "css=#addressLookupWidget-addressLookupQuestionInput-building",
    fallbacks: ["role=textbox[name=/addressLookupWidget-addressLookupQuestionInput-building/i]"],
  },
  addresslookupwidgetAddresslookupquestioninputPostcode: {
    type: "input",
    preferred: "css=#addressLookupWidget-addressLookupQuestionInput-postcode",
    fallbacks: ["role=textbox[name=/addressLookupWidget-addressLookupQuestionInput-postcode/i]"],
  },
  addressOptional: {
    type: "select",
    preferred: "css=#addressLookupQuestionInput",
    fallbacks: ["role=combobox[name=/Address \\(Optional\\)/i]"],
  },
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  day: {
    type: "input",
    preferred: "css=#additionalDriver1DateOfBirthQuestion-day",
    fallbacks: ["css=input[aria-label=\"day\"]", "css=input[placeholder=\"DD\"]", "role=textbox[name=/day/i]"],
  },
  euFull: {
    type: "radio",
    preferred: "css=#additionalDriver1DrivingLicenceTypes4",
    fallbacks: ["css=input[name=\"additionalDriver1DrivingLicenceTypes\"]", "role=textbox[name=/EU Full/i]"],
  },
  euProvisional: {
    type: "radio",
    preferred: "css=#additionalDriver1DrivingLicenceTypes5",
    fallbacks: ["css=input[name=\"additionalDriver1DrivingLicenceTypes\"]", "role=textbox[name=/EU Provisional/i]"],
  },
  findAddress: {
    type: "button",
    preferred: "css=#find-address",
    fallbacks: ["role=button[name=/Find address/i]", "text=/Find address/i"],
  },
  firstName: {
    type: "input",
    preferred: "css=#additionalDriver1FirstNameQuestion",
    fallbacks: ["role=textbox[name=/First name/i]"],
  },
  howLongHaveAdditionalDriverHeldLicenceFor: {
    type: "select",
    preferred: "css=#drivingExpirience",
    fallbacks: ["role=combobox[name=/How long have additional driver held licence for\\?/i]"],
  },
  lastName: {
    type: "input",
    preferred: "css=#additionalDriver1LastNameQuestion",
    fallbacks: ["role=textbox[name=/Last name/i]"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  month: {
    type: "input",
    preferred: "css=#additionalDriver1DateOfBirthQuestion-month",
    fallbacks: ["css=input[aria-label=\"month\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/month/i]"],
  },
  month2: {
    type: "input",
    preferred: "css=#conviction_1_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  month3: {
    type: "input",
    preferred: "css=#conviction_2_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  month4: {
    type: "input",
    preferred: "css=#conviction_3_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  no: {
    type: "radio",
    preferred: "css=#drivingLicenceHandyfalse",
    fallbacks: ["css=input[name=\"drivingLicenceHandy\"]", "role=textbox[name=/No/i]"],
  },
  no2: {
    type: "radio",
    preferred: "css=#hasConvictionsQuestionfalse",
    fallbacks: ["css=input[name=\"hasConvictionsQuestion\"]", "role=textbox[name=/No/i]"],
  },
  no3: {
    type: "radio",
    preferred: "css=#Conviction0ResultedToABanfalse",
    fallbacks: ["css=input[name=\"Conviction0ResultedToABan\"]", "role=textbox[name=/No/i]"],
  },
  no4: {
    type: "radio",
    preferred: "css=#Conviction1ResultedToABanfalse",
    fallbacks: ["css=input[name=\"Conviction1ResultedToABan\"]", "role=textbox[name=/No/i]"],
  },
  no5: {
    type: "radio",
    preferred: "css=#Conviction2ResultedToABanfalse",
    fallbacks: ["css=input[name=\"Conviction2ResultedToABan\"]", "role=textbox[name=/No/i]"],
  },
  other: {
    type: "radio",
    preferred: "css=#additionalDriver1DrivingLicenceTypes6",
    fallbacks: ["css=input[name=\"additionalDriver1DrivingLicenceTypes\"]", "role=textbox[name=/Other/i]"],
  },
  reactSelect13Input: {
    type: "input",
    preferred: "css=#react-select-13-input",
    fallbacks: ["role=textbox[name=/react-select-13-input/i]"],
  },
  reactSelect14Input: {
    type: "input",
    preferred: "css=#react-select-14-input",
    fallbacks: ["role=textbox[name=/react-select-14-input/i]"],
  },
  reactSelect15Input: {
    type: "input",
    preferred: "css=#react-select-15-input",
    fallbacks: ["role=textbox[name=/react-select-15-input/i]"],
  },
  removeConviction: {
    type: "link",
    preferred: "role=link[name=/Remove conviction/i]",
    fallbacks: ["text=/Remove conviction/i"],
  },
  removeConviction2: {
    type: "link",
    preferred: "role=link[name=/Remove conviction/i]",
    fallbacks: ["text=/Remove conviction/i"],
  },
  removeConviction3: {
    type: "link",
    preferred: "role=link[name=/Remove conviction/i]",
    fallbacks: ["text=/Remove conviction/i"],
  },
  title: {
    type: "select",
    preferred: "css=#titleQuestion",
    fallbacks: ["role=combobox[name=/Title/i]"],
  },
  ukFull: {
    type: "radio",
    preferred: "css=#additionalDriver1DrivingLicenceTypes1",
    fallbacks: ["css=input[name=\"additionalDriver1DrivingLicenceTypes\"]", "role=textbox[name=/UK Full/i]"],
  },
  ukFullAutomaticOnly: {
    type: "radio",
    preferred: "css=#additionalDriver1DrivingLicenceTypes2",
    fallbacks: ["css=input[name=\"additionalDriver1DrivingLicenceTypes\"]", "role=textbox[name=/UK Full - Automatic only/i]"],
  },
  ukProvisional: {
    type: "radio",
    preferred: "css=#additionalDriver1DrivingLicenceTypes3",
    fallbacks: ["css=input[name=\"additionalDriver1DrivingLicenceTypes\"]", "role=textbox[name=/UK Provisional/i]"],
  },
  year: {
    type: "input",
    preferred: "css=#additionalDriver1DateOfBirthQuestion-year",
    fallbacks: ["css=input[aria-label=\"year\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/year/i]"],
  },
  year2: {
    type: "input",
    preferred: "css=#conviction_1_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  year3: {
    type: "input",
    preferred: "css=#conviction_2_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  year4: {
    type: "input",
    preferred: "css=#conviction_3_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  yes: {
    type: "radio",
    preferred: "css=#drivingLicenceHandytrue",
    fallbacks: ["css=input[name=\"drivingLicenceHandy\"]", "role=textbox[name=/Yes/i]"],
  },
  yes2: {
    type: "radio",
    preferred: "css=#hasConvictionsQuestiontrue",
    fallbacks: ["css=input[name=\"hasConvictionsQuestion\"]", "role=textbox[name=/Yes/i]"],
  },
  yes3: {
    type: "radio",
    preferred: "css=#Conviction0ResultedToABantrue",
    fallbacks: ["css=input[name=\"Conviction0ResultedToABan\"]", "role=textbox[name=/Yes/i]"],
  },
  yes4: {
    type: "radio",
    preferred: "css=#Conviction1ResultedToABantrue",
    fallbacks: ["css=input[name=\"Conviction1ResultedToABan\"]", "role=textbox[name=/Yes/i]"],
  },
  yes5: {
    type: "radio",
    preferred: "css=#Conviction2ResultedToABantrue",
    fallbacks: ["css=input[name=\"Conviction2ResultedToABan\"]", "role=textbox[name=/Yes/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;