// src/pages/motor/ph-add-driver/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ph-add-driver
// scannedAt: 2026-03-09T13:03:30.698Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.ph-add-driver",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/addDriver/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/addDriver\/[a-z0-9]+/i,
  title: "Add driver",
  titleRe: new RegExp("Add driver", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  back: "back" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  yes: "yes" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;