// src/pages/motor/ph-add-driver/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ph-add-driver
// scannedAt: 2026-03-09T13:03:30.698Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  back: {
    type: "button",
    preferred: "role=button[name=/Back/i]",
    fallbacks: ["text=/Back/i"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#addDriverPolarAnswer",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  no: {
    type: "radio",
    preferred: "css=#addDriverPolarAnswer-false",
    fallbacks: ["css=input[name=\"addDriverPolarAnswer\"]", "role=textbox[name=/No/i]"],
  },
  yes: {
    type: "radio",
    preferred: "css=#addDriverPolarAnswer-true",
    fallbacks: ["css=input[name=\"addDriverPolarAnswer\"]", "role=textbox[name=/Yes/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;