// src/pages/motor/ph-driving-licence-details/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ph-driving-licence-details
// scannedAt: 2026-03-09T12:56:18.999Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.ph-driving-licence-details",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/drivingLicenceScan/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/drivingLicenceScan\/[a-z0-9]+/i,
  title: "Driving licence details",
  titleRe: new RegExp("Driving licence details", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  addFrontOfLicence: "addFrontOfLicence" as ElementKey,
  addFrontOfLicence2: "addFrontOfLicence2" as ElementKey,
  address: "address" as ElementKey,
  addresslookupwidgetAddresslookupquestioninputBuilding: "addresslookupwidgetAddresslookupquestioninputBuilding" as ElementKey,
  addresslookupwidgetAddresslookupquestioninputPostcode: "addresslookupwidgetAddresslookupquestioninputPostcode" as ElementKey,
  back: "back" as ElementKey,
  changeAddress: "changeAddress" as ElementKey,
  day: "day" as ElementKey,
  euFull: "euFull" as ElementKey,
  euProvisional: "euProvisional" as ElementKey,
  findAddress: "findAddress" as ElementKey,
  firstName: "firstName" as ElementKey,
  howLongHaveYouHeldYourLicenceFor: "howLongHaveYouHeldYourLicenceFor" as ElementKey,
  lastName: "lastName" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  month: "month" as ElementKey,
  month2: "month2" as ElementKey,
  month3: "month3" as ElementKey,
  month4: "month4" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  no2: "no2" as ElementKey,
  no3: "no3" as ElementKey,
  no4: "no4" as ElementKey,
  no5: "no5" as ElementKey,
  other: "other" as ElementKey,
  partialdrivinglicencenumberquestionmonthpart: "partialdrivinglicencenumberquestionmonthpart" as ElementKey,
  partialdrivinglicencenumberquestionrandompart: "partialdrivinglicencenumberquestionrandompart" as ElementKey,
  reactSelect2Input: "reactSelect2Input" as ElementKey,
  reactSelect3Input: "reactSelect3Input" as ElementKey,
  reactSelect4Input: "reactSelect4Input" as ElementKey,
  removeConviction: "removeConviction" as ElementKey,
  removeConviction2: "removeConviction2" as ElementKey,
  removeConviction3: "removeConviction3" as ElementKey,
  title: "title" as ElementKey,
  ukFull: "ukFull" as ElementKey,
  ukFullAutomaticOnly: "ukFullAutomaticOnly" as ElementKey,
  ukProvisional: "ukProvisional" as ElementKey,
  year: "year" as ElementKey,
  year2: "year2" as ElementKey,
  year3: "year3" as ElementKey,
  year4: "year4" as ElementKey,
  yes: "yes" as ElementKey,
  yes2: "yes2" as ElementKey,
  yes3: "yes3" as ElementKey,
  yes4: "yes4" as ElementKey,
  yes5: "yes5" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;