// src/scanner/generateElements.ts

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

import { createLogger } from "./logger";

type PageMap = {
    pageKey: string; // e.g. "motor.car-details"
    scannedAt?: string;
    elements: Record<
        string,
        {
            type: string;
            preferred: string;
            fallbacks: string[];
            meta?: any;
        }
    >;
};

type GenOptions = {
    mapsDir: string;
    pagesDir: string;

    // ✅ state is stored outside page-maps
    stateDir?: string;
    stateFile?: string;

    merge?: boolean;
    verbose?: boolean;
    changedOnly?: boolean;
    stateOnly?: boolean;

    // ✅ Level-7 scaffolding (default ON)
    scaffold?: boolean;

    log: ReturnType<typeof createLogger>;
};

type StateFile = Record<string, string>; // mapFile -> hash

// ---------------------------------------------------
// helpers
// ---------------------------------------------------

function safeReadJson<T>(file: string): T | null {
    if (!fs.existsSync(file)) return null;
    return JSON.parse(fs.readFileSync(file, "utf8")) as T;
}

function ensureDir(dir: string) {
    fs.mkdirSync(dir, { recursive: true });
}

function safeWriteText(file: string, content: string) {
    ensureDir(path.dirname(file));
    fs.writeFileSync(file, content, "utf8");
}

function safeWriteTextIfMissing(file: string, content: string): boolean {
    if (fs.existsSync(file)) return false;
    safeWriteText(file, content);
    return true;
}

function hashContent(content: string): string {
    return crypto.createHash("sha1").update(content).digest("hex");
}

function escapeTsString(s: string) {
    // safe for "..." usage
    return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function isValidTsIdentifier(key: string) {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

function toPascal(s: string) {
    return s
        .replace(/[-_.]/g, " ")
        .split(" ")
        .filter(Boolean)
        .map((p) => p[0].toUpperCase() + p.slice(1))
        .join("");
}

function pageKeyToFolder(pagesDir: string, pageKey: string) {
    // motor.car-details -> src/pages/motor/car-details/
    const parts = pageKey.split(".");
    return path.join(pagesDir, ...parts);
}

function mapPageKeyToElementsPath(pagesDir: string, pageKey: string) {
    return path.join(pageKeyToFolder(pagesDir, pageKey), "elements.ts");
}

function mapPageKeyToAliasesGeneratedPath(pagesDir: string, pageKey: string) {
    return path.join(pageKeyToFolder(pagesDir, pageKey), "aliases.generated.ts");
}

function mapPageKeyToAliasesHumanPath(pagesDir: string, pageKey: string) {
    return path.join(pageKeyToFolder(pagesDir, pageKey), "aliases.ts");
}

function mapPageKeyToPageTsPath(pagesDir: string, pageKey: string) {
    const className = `${toPascal(pageKey.split(".").slice(-1)[0] || "Page")}Page`;
    return path.join(pageKeyToFolder(pagesDir, pageKey), `${className}.ts`);
}

function buildElementsTs(pageMap: PageMap): string {
    const lines: string[] = [];

    lines.push(`// AUTO-GENERATED by src/scanner/generateElements.ts`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`// scannedAt: ${pageMap.scannedAt ?? new Date().toISOString()}`);
    lines.push(``);
    lines.push(`export type ElementDef = {`);
    lines.push(`  type: string;`);
    lines.push(`  preferred: string;`);
    lines.push(`  fallbacks: readonly string[];`);
    lines.push(`};`);
    lines.push(``);
    lines.push(`export const elements = {`);

    // Stable order (nice diffs)
    const entries = Object.entries(pageMap.elements).sort(([a], [b]) => a.localeCompare(b));

    for (const [key, v] of entries) {
        const prop = isValidTsIdentifier(key) ? key : JSON.stringify(key);

        lines.push(`  ${prop}: {`);
        lines.push(`    type: "${escapeTsString(v.type)}",`);
        lines.push(`    preferred: "${escapeTsString(v.preferred)}",`);

        const fallbacks = Array.isArray(v.fallbacks) ? v.fallbacks : [];
        if (fallbacks.length) {
            const items = fallbacks.map((f) => `"${escapeTsString(f)}"`).join(", ");
            lines.push(`    fallbacks: [${items}],`);
        } else {
            lines.push(`    fallbacks: [],`);
        }

        lines.push(`  },`);
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type ElementKey = keyof typeof elements;`);

    return lines.join("\n");
}

function buildAliasesGeneratedTs(pageMap: PageMap): string {
    // Machine file: overwrite-safe
    const lines: string[] = [];

    lines.push(`// AUTO-GENERATED by src/scanner/generateElements.ts`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`// scannedAt: ${pageMap.scannedAt ?? new Date().toISOString()}`);
    lines.push(``);
    lines.push(`import type { ElementKey } from "./elements";`);
    lines.push(``);
    lines.push(`// Default alias mapping: alias key == element key`);
    lines.push(`export const aliasesGenerated = {`);

    const keys = Object.keys(pageMap.elements).sort((a, b) => a.localeCompare(b));
    for (const k of keys) {
        const prop = isValidTsIdentifier(k) ? k : JSON.stringify(k);
        lines.push(`  ${prop}: ${JSON.stringify(k)} as ElementKey,`);
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type AliasGeneratedKey = keyof typeof aliasesGenerated;`);

    return lines.join("\n");
}

function buildAliasesHumanTs(pageMap: PageMap): string {
    // Human file: create-only (never overwrite)
    const lines: string[] = [];

    lines.push(`// HUMAN-MAINTAINED FILE`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`//`);
    lines.push(`// Put business-friendly aliases here. Example:`);
    lines.push(`// export const aliases = {`);
    lines.push(`//   continue: "next",`);
    lines.push(`//   vrn: "whatSYourCarRegistrationNumber",`);
    lines.push(`// } as const;`);
    lines.push(``);
    lines.push(`import type { ElementKey } from "./elements";`);
    lines.push(`import { aliasesGenerated } from "./aliases.generated";`);
    lines.push(``);
    lines.push(`// Start empty. You can map business names -> ElementKey.`);
    lines.push(`export const aliases = {`);
    lines.push(`  // example: continue: aliasesGenerated.next,`);
    lines.push(`} as const satisfies Record<string, ElementKey>;`);
    lines.push(``);
    lines.push(`export const allAliases = { ...aliasesGenerated, ...aliases } as const;`);
    lines.push(`export type AliasKey = keyof typeof allAliases;`);

    return lines.join("\n");
}

function buildPageTsStub(pageMap: PageMap): string {
    const pageKey = pageMap.pageKey;
    const lastSeg = pageKey.split(".").slice(-1)[0] || "page";
    const className = `${toPascal(lastSeg)}Page`;

    const lines: string[] = [];
    lines.push(`// AUTO-SCAFFOLDED (create-only) by src/scanner/generateElements.ts`);
    lines.push(`// pageKey: ${pageKey}`);
    lines.push(``);
    lines.push(`import type { Page } from "@playwright/test";`);
    lines.push(`import { BasePage } from "../../core/BasePage"; // adjust if needed`);
    lines.push(`import { elements, type ElementKey } from "./elements";`);
    lines.push(``);
    lines.push(`const PAGE_KEY = ${JSON.stringify(pageKey)} as const;`);
    lines.push(``);
    lines.push(`export class ${className} extends BasePage {`);
    lines.push(`  constructor(page: Page) {`);
    lines.push(`    super(page);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  // --- key-aware helpers (self-heal capable) ---`);
    lines.push(`  async click<K extends ElementKey>(key: K) {`);
    lines.push(`    await this.clickByKey(PAGE_KEY, String(key), elements[key]);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  async fill<K extends ElementKey>(key: K, value: string) {`);
    lines.push(`    await this.fillByKey(PAGE_KEY, String(key), elements[key], value);`);
    lines.push(`  }`);
    lines.push(``);
    lines.push(`  async selectOption<K extends ElementKey>(key: K, value: string) {`);
    lines.push(`    await this.selectOptionByKey(PAGE_KEY, String(key), elements[key], value);`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push(``);

    return lines.join("\n");
}

// ---------------------------------------------------
// main
// ---------------------------------------------------

async function generateElements(opts: GenOptions) {
    const log = opts.log;

    const scaffold = opts.scaffold !== false; // default true

    const stateDir = opts.stateDir ?? path.join(process.cwd(), "src", ".scanner-state");
    ensureDir(stateDir);

    const stateFilePath = opts.stateFile ?? path.join(stateDir, "page-maps-state.json");

    const oldState: StateFile = safeReadJson<StateFile>(stateFilePath) ?? {};
    const newState: StateFile = {};

    // ✅ ignore dotfiles like .page-maps-state.json (or any future hidden json)
    const mapFiles = fs
        .readdirSync(opts.mapsDir)
        .filter((f) => f.endsWith(".json") && !f.startsWith("."));

    log.info(`Found ${mapFiles.length} page-map(s).`);

    let processed = 0;

    for (const file of mapFiles) {
        const abs = path.join(opts.mapsDir, file);
        const raw = fs.readFileSync(abs, "utf8");

        const hash = hashContent(raw);
        newState[file] = hash;

        const oldHash = oldState[file];
        const changed = oldHash !== hash;

        if (opts.changedOnly && !changed) {
            if (opts.verbose) log.debug(`UNCHANGED → skipping ${file}`);
            continue;
        }

        const pageMap = JSON.parse(raw) as PageMap;
        if (!pageMap?.pageKey) throw new Error(`Invalid page-map (missing pageKey): ${file}`);
        if (!pageMap?.elements || typeof pageMap.elements !== "object") {
            throw new Error(`Invalid page-map (missing elements): ${file}`);
        }

        const pageFolder = pageKeyToFolder(opts.pagesDir, pageMap.pageKey);
        const elementsPath = mapPageKeyToElementsPath(opts.pagesDir, pageMap.pageKey);
        const aliasesGenPath = mapPageKeyToAliasesGeneratedPath(opts.pagesDir, pageMap.pageKey);
        const aliasesHumanPath = mapPageKeyToAliasesHumanPath(opts.pagesDir, pageMap.pageKey);
        const pageTsPath = mapPageKeyToPageTsPath(opts.pagesDir, pageMap.pageKey);

        // Level-7: ensure folder/files exist (create-only where required)
        if (scaffold) {
            ensureDir(pageFolder);

            // create-only
            const createdAliases = safeWriteTextIfMissing(aliasesHumanPath, buildAliasesHumanTs(pageMap));
            if (createdAliases) log.info(`Scaffolded: ${aliasesHumanPath}`);

            const createdPage = safeWriteTextIfMissing(pageTsPath, buildPageTsStub(pageMap));
            if (createdPage) log.info(`Scaffolded: ${pageTsPath}`);

            // overwrite-safe (regenerate)
            safeWriteText(aliasesGenPath, buildAliasesGeneratedTs(pageMap));
            if (opts.verbose) log.debug(`Generated: ${aliasesGenPath}`);
        }

        if (opts.stateOnly) {
            if (opts.verbose) log.debug(`STATE-ONLY → skipping write for ${pageMap.pageKey}`);
            processed++;
            continue;
        }

        const ts = buildElementsTs(pageMap);

        // elements.ts (write/merge flag is only informational right now because we regenerate it)
        if (opts.merge && fs.existsSync(elementsPath)) {
            log.info(`Merging (overwrite-safe): ${elementsPath}`);
        } else {
            log.info(`Writing: ${elementsPath}`);
        }
        safeWriteText(elementsPath, ts);

        processed++;
    }

    // always update state file (even if stateOnly=true)
    safeWriteText(stateFilePath, JSON.stringify(newState, null, 2));

    log.info(`State file updated: ${stateFilePath}`);
    log.info(`Processed pages: ${processed}`);
}

// ---------------------------------------------------
// CLI
// ---------------------------------------------------

function hasFlag(name: string) {
    return process.argv.includes(name);
}

(async () => {
    const log = createLogger({
        prefix: "[scanner]",
        verbose: hasFlag("--verbose"),
    });

    const mapsDir = path.join(process.cwd(), "src", "page-maps");
    const pagesDir = path.join(process.cwd(), "src", "pages");

    // ✅ central scanner state folder (not inside page-maps)
    const stateDir = path.join(process.cwd(), "src", ".scanner-state");
    const stateFile = path.join(stateDir, "page-maps-state.json");

    const opts: GenOptions = {
        mapsDir,
        pagesDir,
        stateDir,
        stateFile,

        merge: hasFlag("--merge"),
        verbose: hasFlag("--verbose"),
        changedOnly: hasFlag("--changedOnly"),
        stateOnly: hasFlag("--stateOnly"),

        // Level-7 on by default; allow opt-out with --noScaffold
        scaffold: !hasFlag("--noScaffold"),

        log,
    };

    try {
        log.info("Generating elements from page-maps...");
        await generateElements(opts);
        log.info("Done ✅");
    } catch (e: any) {
        log.error(e?.message || String(e));
        process.exit(1);
    }
})();