// src/scanner/generateElements.ts

import fs from "node:fs";
import path from "node:path";
import { createLogger } from "./logger";
import type { PageMap } from "./types";

type GenOptions = {
    pageKey?: string;          // generate only one pageKey
    mapsDir?: string;          // default: ./src/page-maps
    pagesDir?: string;         // default: ./src/pages
    outFileName?: string;      // default: elements.ts
    merge?: boolean;           // default: true (enterprise safe)
    dryRun?: boolean;          // default: false
    verbose?: boolean;         // debug logs
};

function ensureDir(dir: string) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function safeReadJson<T>(filePath: string): T {
    return JSON.parse(fs.readFileSync(filePath, "utf8")) as T;
}

/**
 * pageKey -> pages folder mapping rule:
 * - pageKey uses dots: "motor.car-details"
 * - maps to folders:   "src/pages/motor/car-details/elements.ts"
 */
function pageKeyToElementsPath(pageKey: string, pagesDirAbs: string, outFileName: string) {
    const parts = pageKey.split(".").filter(Boolean);
    return path.join(pagesDirAbs, ...parts, outFileName);
}

function buildElementsTs(pageKey: string, map: PageMap): string {
    // stable output ordering
    const keys = Object.keys(map.elements).sort((a, b) => a.localeCompare(b));

    // Build typed object with preferred + fallbacks
    const lines: string[] = [];
    lines.push(`// AUTO-GENERATED by scanner generateElements.ts`);
    lines.push(`// pageKey: ${pageKey}`);
    lines.push(`// scannedAt: ${map.scannedAt}`);
    lines.push(``);
    lines.push(`export type ElementDef = {`);
    lines.push(`  type: string;`);
    lines.push(`  preferred: string;`);
    lines.push(`  fallbacks: string[];`);
    lines.push(`};`);
    lines.push(``);
    lines.push(`export const elements = {`);

    for (const k of keys) {
        const el = map.elements[k];
        const preferred = JSON.stringify(el.preferred ?? "");
        const fallbacks = JSON.stringify(el.fallbacks ?? [], null, 0);

        // Keep it readable and consistent
        lines.push(`  ${JSON.stringify(k)}: {`);
        lines.push(`    type: ${JSON.stringify(el.type ?? "element")},`);
        lines.push(`    preferred: ${preferred},`);
        lines.push(`    fallbacks: ${fallbacks},`);
        lines.push(`  },`);
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type ElementKey = keyof typeof elements;`);
    lines.push(``);
    return lines.join("\n");
}

/**
 * Enterprise-safe merge:
 * - Keeps existing keys
 * - Adds new keys
 * - If preferred differs: keep old preferred in fallbacks and promote new preferred
 * - Union fallbacks
 *
 * NOTE: merge happens on JSON shape, then re-rendered to TS.
 */
function mergeMaps(existing: PageMap, incoming: PageMap): PageMap {
    const out: PageMap = {
        ...existing,
        pageKey: existing.pageKey || incoming.pageKey,
        url: incoming.url || existing.url,
        urlPath: incoming.urlPath ?? existing.urlPath,
        scannedAt: incoming.scannedAt,
        elements: { ...existing.elements },
    };

    for (const [key, next] of Object.entries(incoming.elements)) {
        const cur = out.elements[key];

        if (!cur) {
            out.elements[key] = next;
            continue;
        }

        const curPreferred = cur.preferred;
        const nextPreferred = next.preferred;

        const set = new Set<string>([
            ...(cur.fallbacks ?? []),
            ...(next.fallbacks ?? []),
        ]);

        if (curPreferred && nextPreferred && curPreferred !== nextPreferred) {
            set.add(curPreferred);
            set.delete(nextPreferred);
            out.elements[key] = {
                ...cur,
                ...next,
                preferred: nextPreferred,
                fallbacks: Array.from(set),
                meta: {
                    ...(cur.meta ?? {}),
                    ...(next.meta ?? {}),
                    tag: (next.meta?.tag ?? cur.meta?.tag ?? next.type ?? cur.type ?? "element") as string,
                },
            };
        } else {
            out.elements[key] = {
                ...cur,
                ...next,
                preferred: nextPreferred ?? curPreferred,
                fallbacks: Array.from(set),
                meta: {
                    ...(cur.meta ?? {}),
                    ...(next.meta ?? {}),
                    tag: (next.meta?.tag ?? cur.meta?.tag ?? next.type ?? cur.type ?? "element") as string,
                },
            };
        }
    }

    return out;
}

function listMapFiles(mapsDirAbs: string): string[] {
    if (!fs.existsSync(mapsDirAbs)) return [];
    return fs
        .readdirSync(mapsDirAbs)
        .filter((f) => f.endsWith(".json"))
        .map((f) => path.join(mapsDirAbs, f));
}

export async function generateElements(opts: GenOptions = {}) {
    const log = createLogger({
        prefix: "[scanner]",
        verbose: !!opts.verbose,
        withTimestamp: true,
    });

    const mapsDirAbs = path.resolve(opts.mapsDir ?? path.join(process.cwd(), "src", "page-maps"));
    const pagesDirAbs = path.resolve(opts.pagesDir ?? path.join(process.cwd(), "src", "pages"));
    const outFileName = opts.outFileName ?? "elements.ts";
    const merge = opts.merge !== false; // default TRUE
    const dryRun = !!opts.dryRun;

    log.info(`Generating elements.ts from page-maps...`);
    log.info(`Maps dir: ${mapsDirAbs}`);
    log.info(`Pages dir: ${pagesDirAbs}`);
    log.info(`Mode: ${merge ? "merge" : "overwrite"}${dryRun ? " (dry-run)" : ""}`);

    const files = listMapFiles(mapsDirAbs);
    if (!files.length) {
        throw new Error(`No page-map JSON found in: ${mapsDirAbs}`);
    }

    // Filter by pageKey if provided
    const toProcess = opts.pageKey
        ? files.filter((f) => path.basename(f, ".json") === opts.pageKey)
        : files;

    if (opts.pageKey && !toProcess.length) {
        const available = files.map((f) => path.basename(f, ".json")).sort().join(", ");
        throw new Error(`pageKey '${opts.pageKey}' not found. Available: ${available}`);
    }

    for (const file of toProcess) {
        const incoming = safeReadJson<PageMap>(file);
        const pageKey = incoming.pageKey || path.basename(file, ".json");

        const outPath = pageKeyToElementsPath(pageKey, pagesDirAbs, outFileName);
        ensureDir(path.dirname(outPath));

        let finalMap = incoming;

        if (merge && fs.existsSync(outPath)) {
            // We can't read TS back into PageMap, so merge at JSON level by using the JSON map itself.
            // Therefore: if merge requested and elements.ts exists, we also look for existing JSON map to merge.
            // Best practice: always merge via page-map JSON (source of truth), not TS.
            // So we try to find the existing JSON file for this pageKey and merge it with incoming (incoming wins).
            const existingJsonPath = path.join(mapsDirAbs, `${pageKey}.json`);
            if (fs.existsSync(existingJsonPath)) {
                const existing = safeReadJson<PageMap>(existingJsonPath);
                finalMap = mergeMaps(existing, incoming);
            }
        }

        const ts = buildElementsTs(pageKey, finalMap);

        log.info(`Writing: ${outPath}`);
        if (!dryRun) {
            fs.writeFileSync(outPath, ts, "utf8");
        }

        log.debug(`Done pageKey=${pageKey} keys=${Object.keys(finalMap.elements).length}`);
    }

    log.info(`Done ✅`);
}

/**
 * Optional CLI usage:
 *   npx ts-node src/scanner/generateElements.ts -- --pageKey motor.car-details --merge --verbose
 *
 * (We keep it simple: parse args manually here.)
 */
function getArg(name: string): string | null {
    const idx = process.argv.indexOf(name);
    if (idx === -1) return null;
    return process.argv[idx + 1] ?? null;
}

function hasFlag(name: string): boolean {
    return process.argv.includes(name);
}

// Allow running directly
if (require.main === module) {
    const pageKey = getArg("--pageKey") ?? undefined;
    const mapsDir = getArg("--mapsDir") ?? undefined;
    const pagesDir = getArg("--pagesDir") ?? undefined;
    const merge = hasFlag("--overwrite") ? false : true; // default merge; use --overwrite to disable
    const dryRun = hasFlag("--dryRun");
    const verbose = hasFlag("--verbose");

    generateElements({ pageKey, mapsDir, pagesDir, merge, dryRun, verbose }).catch((e) => {
        // eslint-disable-next-line no-console
        console.error(e);
        process.exit(1);
    });
}