// src/scanner/generateElements.ts

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

import { createLogger } from "./logger";

type PageMap = {
    pageKey: string;
    elements: Record<
        string,
        {
            type: string;
            preferred: string;
            fallbacks: string[];
        }
    >;
};

type GenOptions = {
    mapsDir: string;
    pagesDir: string;

    // ✅ state is stored outside page-maps
    stateDir?: string;
    stateFile?: string;

    merge?: boolean;
    verbose?: boolean;
    changedOnly?: boolean;
    stateOnly?: boolean;

    log: ReturnType<typeof createLogger>;
};

type StateFile = Record<string, string>; // mapFile -> hash

// ---------------------------------------------------
// helpers
// ---------------------------------------------------

function safeReadJson<T>(file: string): T | null {
    if (!fs.existsSync(file)) return null;
    return JSON.parse(fs.readFileSync(file, "utf8")) as T;
}

function safeWriteText(file: string, content: string) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, "utf8");
}

function hashContent(content: string): string {
    return crypto.createHash("sha1").update(content).digest("hex");
}

function escapeTsString(s: string) {
    // safe for "..." usage
    return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function isValidTsIdentifier(key: string) {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

function mapPageKeyToElementsPath(pagesDir: string, pageKey: string) {
    // example: motor.car-details -> src/pages/motor/car-details/elements.ts
    const parts = pageKey.split(".");
    const folder = path.join(pagesDir, ...parts);
    return path.join(folder, "elements.ts");
}

function buildTs(pageMap: PageMap): string {
    const lines: string[] = [];

    lines.push(`// AUTO-GENERATED by src/scanner/generateElements.ts`);
    lines.push(`// pageKey: ${pageMap.pageKey}`);
    lines.push(`// scannedAt: ${new Date().toISOString()}`);
    lines.push(``);
    lines.push(`export type ElementDef = {`);
    lines.push(`  type: string;`);
    lines.push(`  preferred: string;`);
    lines.push(`  fallbacks: readonly string[];`);
    lines.push(`};`);
    lines.push(``);
    lines.push(`export const elements = {`);

    // Stable order (nice diffs)
    const entries = Object.entries(pageMap.elements).sort(([a], [b]) => a.localeCompare(b));

    for (const [key, v] of entries) {
        const prop = isValidTsIdentifier(key) ? key : JSON.stringify(key);

        lines.push(`  ${prop}: {`);
        lines.push(`    type: "${escapeTsString(v.type)}",`);
        lines.push(`    preferred: "${escapeTsString(v.preferred)}",`);

        const fallbacks = Array.isArray(v.fallbacks) ? v.fallbacks : [];
        if (fallbacks.length) {
            const items = fallbacks.map((f) => `"${escapeTsString(f)}"`).join(", ");
            lines.push(`    fallbacks: [${items}],`);
        } else {
            lines.push(`    fallbacks: [],`);
        }

        lines.push(`  },`);
    }

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type ElementKey = keyof typeof elements;`);

    return lines.join("\n");
}

// ---------------------------------------------------
// main
// ---------------------------------------------------

async function generateElements(opts: GenOptions) {
    const log = opts.log;

    const stateDir = opts.stateDir ?? path.join(process.cwd(), "src", ".scanner-state");
    if (!fs.existsSync(stateDir)) fs.mkdirSync(stateDir, { recursive: true });

    const stateFilePath = opts.stateFile ?? path.join(stateDir, "page-maps-state.json");

    const oldState: StateFile = safeReadJson<StateFile>(stateFilePath) ?? {};
    const newState: StateFile = {};

    // ✅ ignore dotfiles like .page-maps-state.json (or any future hidden json)
    const mapFiles = fs
        .readdirSync(opts.mapsDir)
        .filter((f) => f.endsWith(".json") && !f.startsWith("."));

    log.info(`Found ${mapFiles.length} page-map(s).`);

    let processed = 0;

    for (const file of mapFiles) {
        const abs = path.join(opts.mapsDir, file);
        const raw = fs.readFileSync(abs, "utf8");

        const hash = hashContent(raw);
        newState[file] = hash;

        const oldHash = oldState[file];
        const changed = oldHash !== hash;

        if (opts.changedOnly && !changed) {
            if (opts.verbose) log.debug(`UNCHANGED → skipping ${file}`);
            continue;
        }

        const pageMap = JSON.parse(raw) as PageMap;
        if (!pageMap?.pageKey) {
            throw new Error(`Invalid page-map (missing pageKey): ${file}`);
        }
        if (!pageMap?.elements || typeof pageMap.elements !== "object") {
            throw new Error(`Invalid page-map (missing elements): ${file}`);
        }

        const outPath = mapPageKeyToElementsPath(opts.pagesDir, pageMap.pageKey);

        if (opts.stateOnly) {
            if (opts.verbose) log.debug(`STATE-ONLY → skipping write for ${pageMap.pageKey}`);
            processed++;
            continue;
        }

        const ts = buildTs(pageMap);

        if (opts.merge && fs.existsSync(outPath)) {
            log.info(`Merging (overwrite-safe): ${outPath}`);
        } else {
            log.info(`Writing: ${outPath}`);
        }

        safeWriteText(outPath, ts);
        processed++;
    }

    // always update state file (even if stateOnly=true)
    safeWriteText(stateFilePath, JSON.stringify(newState, null, 2));

    log.info(`State file updated: ${stateFilePath}`);
    log.info(`Processed pages: ${processed}`);
}

// ---------------------------------------------------
// CLI
// ---------------------------------------------------

function hasFlag(name: string) {
    return process.argv.includes(name);
}

(async () => {
    const log = createLogger({
        prefix: "[scanner]",
        verbose: hasFlag("--verbose"),
    });

    const mapsDir = path.join(process.cwd(), "src", "page-maps");
    const pagesDir = path.join(process.cwd(), "src", "pages");

    // ✅ central scanner state folder (not inside page-maps)
    const stateDir = path.join(process.cwd(), "src", ".scanner-state");
    const stateFile = path.join(stateDir, "page-maps-state.json");

    const opts: GenOptions = {
        mapsDir,
        pagesDir,
        stateDir,
        stateFile,

        merge: hasFlag("--merge"),
        verbose: hasFlag("--verbose"),
        changedOnly: hasFlag("--changedOnly"),
        stateOnly: hasFlag("--stateOnly"),
        log,
    };

    try {
        log.info("Generating elements from page-maps...");
        await generateElements(opts);
        log.info("Done ✅");
    } catch (e: any) {
        log.error(e?.message || String(e));
        process.exit(1);
    }
})();