// src/businessLayer/pageActions/registry/pageActionsRegistry.ts
// AUTO-GENERATED by pageActions generator

import { athena } from "./athena";

export const pageActionsRegistry = {
    athena,
} as const;
