// src/pages/motor/ad-personal-details/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ad-personal-details
// scannedAt: 2026-03-09T13:10:29.991Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.ad-personal-details",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/additionalDriver1PersonalDetailsPage/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/additionalDriver1PersonalDetailsPage\/[a-z0-9]+/i,
  title: "Personal details for additional driver",
  titleRe: new RegExp("Personal details for additional driver", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  "12Years": "12Years" as ElementKey,
  "23Years": "23Years" as ElementKey,
  back: "back" as ElementKey,
  closeAlert: "closeAlert" as ElementKey,
  lessThan1Year: "lessThan1Year" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  no2: "no2" as ElementKey,
  pleaseChooseTheTypeOfDriverSEducation: "pleaseChooseTheTypeOfDriverSEducation" as ElementKey,
  reactSelect16Input: "reactSelect16Input" as ElementKey,
  reactSelect17Input: "reactSelect17Input" as ElementKey,
  reactSelect18Input: "reactSelect18Input" as ElementKey,
  reactSelect19Input: "reactSelect19Input" as ElementKey,
  reactSelect20Input: "reactSelect20Input" as ElementKey,
  reactSelect21Input: "reactSelect21Input" as ElementKey,
  whatSDriverSEmploymentStatus: "whatSDriverSEmploymentStatus" as ElementKey,
  whatSDriverSMaritalStatus: "whatSDriverSMaritalStatus" as ElementKey,
  whatSDriverSRelationshipToAccountHolder: "whatSDriverSRelationshipToAccountHolder" as ElementKey,
  yes: "yes" as ElementKey,
  yes2: "yes2" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;