// src/pages/motor/ad-personal-details/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ad-personal-details
// scannedAt: 2026-03-09T13:10:29.991Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  "12Years": {
    type: "radio",
    preferred: "css=#residencyTerm2",
    fallbacks: ["css=input[name=\"residencyTerm\"]", "role=textbox[name=/1 - 2 years/i]"],
  },
  "23Years": {
    type: "radio",
    preferred: "css=#residencyTerm3",
    fallbacks: ["css=input[name=\"residencyTerm\"]", "role=textbox[name=/2 - 3 years/i]"],
  },
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  closeAlert: {
    type: "button",
    preferred: "css=button[aria-label=\"close alert\"]",
    fallbacks: ["role=button[name=/close alert/i]"],
  },
  lessThan1Year: {
    type: "radio",
    preferred: "css=#residencyTerm1",
    fallbacks: ["css=input[name=\"residencyTerm\"]", "role=textbox[name=/Less than 1 year/i]"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  no: {
    type: "radio",
    preferred: "css=#haveSecondaryOccupationfalse",
    fallbacks: ["css=input[name=\"haveSecondaryOccupation\"]", "role=textbox[name=/No/i]"],
  },
  no2: {
    type: "radio",
    preferred: "css=#residenceOfUKTermfalse",
    fallbacks: ["css=input[name=\"residenceOfUKTerm\"]", "role=textbox[name=/No/i]"],
  },
  pleaseChooseTheTypeOfDriverSEducation: {
    type: "select",
    preferred: "css=#additionalDriver1EducationQuestion",
    fallbacks: ["role=combobox[name=/Please choose the type of driver's education/i]"],
  },
  reactSelect16Input: {
    type: "input",
    preferred: "css=#react-select-16-input",
    fallbacks: ["role=textbox[name=/react-select-16-input/i]"],
  },
  reactSelect17Input: {
    type: "input",
    preferred: "css=#react-select-17-input",
    fallbacks: ["role=textbox[name=/react-select-17-input/i]"],
  },
  reactSelect18Input: {
    type: "input",
    preferred: "css=#react-select-18-input",
    fallbacks: ["role=textbox[name=/react-select-18-input/i]"],
  },
  reactSelect19Input: {
    type: "input",
    preferred: "css=#react-select-19-input",
    fallbacks: ["role=textbox[name=/react-select-19-input/i]"],
  },
  reactSelect20Input: {
    type: "input",
    preferred: "css=#react-select-20-input",
    fallbacks: ["role=textbox[name=/react-select-20-input/i]"],
  },
  reactSelect21Input: {
    type: "input",
    preferred: "css=#react-select-21-input",
    fallbacks: ["role=textbox[name=/react-select-21-input/i]"],
  },
  whatSDriverSEmploymentStatus: {
    type: "select",
    preferred: "css=#additionalDriver1EmploymentStatusQuestion",
    fallbacks: ["role=combobox[name=/What's driver's employment status\\?/i]"],
  },
  whatSDriverSMaritalStatus: {
    type: "select",
    preferred: "css=#additionalDriver1MaritalStatusQuestion",
    fallbacks: ["role=combobox[name=/What's driver's marital status\\?/i]"],
  },
  whatSDriverSRelationshipToAccountHolder: {
    type: "select",
    preferred: "css=#additionalDriver1RelationshipToAccountHolderQuestion",
    fallbacks: ["role=combobox[name=/What's driver's relationship to account holder\\?/i]"],
  },
  yes: {
    type: "radio",
    preferred: "css=#haveSecondaryOccupationtrue",
    fallbacks: ["css=input[name=\"haveSecondaryOccupation\"]", "role=textbox[name=/Yes/i]"],
  },
  yes2: {
    type: "radio",
    preferred: "css=#residenceOfUKTermtrue",
    fallbacks: ["css=input[name=\"residenceOfUKTerm\"]", "role=textbox[name=/Yes/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;