// src/pages/motor/car-usage/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.car-usage
// scannedAt: 2026-03-09T13:12:39.305Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.car-usage",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/additionalCarDetails/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/additionalCarDetails\/[a-z0-9]+/i,
  title: "Car Usage",
  titleRe: new RegExp("Car Usage", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  "1": "1" as ElementKey,
  "2": "2" as ElementKey,
  "3": "3" as ElementKey,
  "4": "4" as ElementKey,
  "5": "5" as ElementKey,
  "6": "6" as ElementKey,
  addAnotherDriver: "addAnotherDriver" as ElementKey,
  back: "back" as ElementKey,
  businessUseCommercial: "businessUseCommercial" as ElementKey,
  businessUseNonCommercial: "businessUseNonCommercial" as ElementKey,
  drive: "drive" as ElementKey,
  garage: "garage" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  maindriver: "maindriver" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  registeredkeeper: "registeredkeeper" as ElementKey,
  registeredkeeper2: "registeredkeeper2" as ElementKey,
  road: "road" as ElementKey,
  securedCarPark: "securedCarPark" as ElementKey,
  socialDomesticAndPleasure: "socialDomesticAndPleasure" as ElementKey,
  socialDomesticPleasureAndCommutingSdpC: "socialDomesticPleasureAndCommutingSdpC" as ElementKey,
  tomAlleneditdelete: "tomAlleneditdelete" as ElementKey,
  tomAlleneditdelete2: "tomAlleneditdelete2" as ElementKey,
  tomAlleneditdelete3: "tomAlleneditdelete3" as ElementKey,
  unsecuredCarPark: "unsecuredCarPark" as ElementKey,
  vjTomaredit: "vjTomaredit" as ElementKey,
  vjTomaredit2: "vjTomaredit2" as ElementKey,
  whatIsThisMiniCooperSh11ukaUsedFor: "whatIsThisMiniCooperSh11ukaUsedFor" as ElementKey,
  whatSYourEstimatedAnnualMileage: "whatSYourEstimatedAnnualMileage" as ElementKey,
  whereIsThisCarKeptPleaseEnterPostCodeOnly: "whereIsThisCarKeptPleaseEnterPostCodeOnly" as ElementKey,
  yes: "yes" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;