// src/pages/motor/car-usage/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.car-usage
// scannedAt: 2026-03-09T13:12:39.305Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  "1": {
    type: "radio",
    preferred: "css=#carsInHouseholdQuestionInput1",
    fallbacks: ["css=input[name=\"carsInHouseholdQuestionInput\"]", "role=textbox[name=/1/i]"],
  },
  "2": {
    type: "radio",
    preferred: "css=#carsInHouseholdQuestionInput2",
    fallbacks: ["css=input[name=\"carsInHouseholdQuestionInput\"]", "role=textbox[name=/2/i]"],
  },
  "3": {
    type: "radio",
    preferred: "css=#carsInHouseholdQuestionInput3",
    fallbacks: ["css=input[name=\"carsInHouseholdQuestionInput\"]", "role=textbox[name=/3/i]"],
  },
  "4": {
    type: "radio",
    preferred: "css=#carsInHouseholdQuestionInput4",
    fallbacks: ["css=input[name=\"carsInHouseholdQuestionInput\"]", "role=textbox[name=/4/i]"],
  },
  "5": {
    type: "radio",
    preferred: "css=#carsInHouseholdQuestionInput5",
    fallbacks: ["css=input[name=\"carsInHouseholdQuestionInput\"]", "role=textbox[name=/5/i]"],
  },
  "6": {
    type: "radio",
    preferred: "css=#carsInHouseholdQuestionInput6",
    fallbacks: ["css=input[name=\"carsInHouseholdQuestionInput\"]", "role=textbox[name=/6\\+/i]"],
  },
  addAnotherDriver: {
    type: "link",
    preferred: "role=link[name=/Add another driver/i]",
    fallbacks: ["text=/Add another driver/i"],
  },
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  businessUseCommercial: {
    type: "radio",
    preferred: "css=#carUsageChoice-BU-Class3",
    fallbacks: ["css=input[name=\"carUsageChoice-BU-Class3\"]", "role=textbox[name=/Business use commercial/i]"],
  },
  businessUseNonCommercial: {
    type: "radio",
    preferred: "css=#carUsageChoice-BU-Class1",
    fallbacks: ["css=input[name=\"carUsageChoice-BU-Class1\"]", "role=textbox[name=/Business use non-commercial/i]"],
  },
  drive: {
    type: "radio",
    preferred: "css=#overNightPlace1",
    fallbacks: ["css=input[name=\"overNightPlace\"]", "role=textbox[name=/Drive/i]"],
  },
  garage: {
    type: "radio",
    preferred: "css=#overNightPlace2",
    fallbacks: ["css=input[name=\"overNightPlace\"]", "role=textbox[name=/Garage/i]"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  maindriver: {
    type: "select",
    preferred: "css=#mainDriver",
    fallbacks: ["role=combobox[name=/mainDriver/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  no: {
    type: "radio",
    preferred: "css=#overnightLocationIsHomefalse",
    fallbacks: ["css=input[name=\"overnightLocationIsHome\"]", "role=textbox[name=/No/i]"],
  },
  registeredkeeper: {
    type: "select",
    preferred: "css=#registeredKeeper",
    fallbacks: ["role=combobox[name=/registeredKeeper/i]"],
  },
  registeredkeeper2: {
    type: "select",
    preferred: "css=#registeredKeeper",
    fallbacks: ["role=combobox[name=/registeredKeeper/i]"],
  },
  road: {
    type: "radio",
    preferred: "css=#overNightPlace3",
    fallbacks: ["css=input[name=\"overNightPlace\"]", "role=textbox[name=/Road/i]"],
  },
  securedCarPark: {
    type: "radio",
    preferred: "css=#overNightPlace4",
    fallbacks: ["css=input[name=\"overNightPlace\"]", "role=textbox[name=/Secured car park/i]"],
  },
  socialDomesticAndPleasure: {
    type: "radio",
    preferred: "css=#carUsageChoice-SDP",
    fallbacks: ["css=input[name=\"carUsageChoice-SDP\"]", "role=textbox[name=/Social, Domestic and Pleasure/i]"],
  },
  socialDomesticPleasureAndCommutingSdpC: {
    type: "radio",
    preferred: "css=#carUsageChoice-SDP+C",
    fallbacks: ["css=input[name=\"carUsageChoice-SDP+C\"]", "role=textbox[name=/Social, Domestic, Pleasure and Commuting \\(SDP\\+C\\)/i]"],
  },
  tomAlleneditdelete: {
    type: "checkbox",
    preferred: "css=#89500a49-d935-44a2-97ce-648e2ab6a877",
    fallbacks: ["css=input[aria-label=\"Tom Allen\"]", "role=textbox[name=/Tom Allen/i]"],
  },
  tomAlleneditdelete2: {
    type: "link",
    preferred: "css=#edit-1",
    fallbacks: ["role=link[name=/Edit/i]", "text=/Edit/i"],
  },
  tomAlleneditdelete3: {
    type: "link",
    preferred: "css=#delete-89500a49-d935-44a2-97ce-648e2ab6a877",
    fallbacks: ["role=link[name=/Delete/i]", "text=/Delete/i"],
  },
  unsecuredCarPark: {
    type: "radio",
    preferred: "css=#overNightPlace5",
    fallbacks: ["css=input[name=\"overNightPlace\"]", "role=textbox[name=/Unsecured car park/i]"],
  },
  vjTomaredit: {
    type: "checkbox",
    preferred: "css=#ef1e466f-f71f-41a4-96eb-0ef53d586e1a",
    fallbacks: ["css=input[aria-label=\"VJ Tomar\"]", "role=textbox[name=/VJ Tomar/i]"],
  },
  vjTomaredit2: {
    type: "link",
    preferred: "css=#edit-0",
    fallbacks: ["role=link[name=/Edit/i]", "text=/Edit/i"],
  },
  whatIsThisMiniCooperSh11ukaUsedFor: {
    type: "button",
    preferred: "css=div[aria-label=\"Info button for more information about car usage\"]",
    fallbacks: ["role=button[name=/Info button for more information about car usage/i]"],
  },
  whatSYourEstimatedAnnualMileage: {
    type: "select",
    preferred: "css=#mileage",
    fallbacks: ["role=combobox[name=/What's your estimated annual mileage\\?/i]"],
  },
  whereIsThisCarKeptPleaseEnterPostCodeOnly: {
    type: "input",
    preferred: "css=#overnightPostcode",
    fallbacks: ["role=textbox[name=/Where is this car kept\\? Please enter post code only\\./i]"],
  },
  yes: {
    type: "radio",
    preferred: "css=#overnightLocationIsHometrue",
    fallbacks: ["css=input[name=\"overnightLocationIsHome\"]", "role=textbox[name=/Yes/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;