// AUTO-GENERATED by src/scanner/generateElements.ts
// pageKey: common.direct-debit-setup
// scannedAt: 2026-02-27T11:57:12.775Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: string[];
};

export const elements = {
  "2": {
    type: "link",
    preferred: "role=link[name=/___/i]",
    fallbacks: ["text=/___/i"],
  },
  "allowAll": {
    type: "button",
    preferred: "css=#accept-recommended-btn-handler",
    fallbacks: ["role=button[name=/Allow All/i]","text=/Allow All/i"],
  },
  "apply": {
    type: "button",
    preferred: "css=#filter-apply-handler",
    fallbacks: ["role=button[name=/Apply/i]","text=/Apply/i"],
  },
  "back": {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]","text=/Back/i"],
  },
  "back2": {
    type: "button",
    preferred: "css=button[aria-label=\"Back\"]",
    fallbacks: ["role=button[name=/Back Button/i]","text=/Back Button/i"],
  },
  "button51": {
    type: "button",
    preferred: "css=button",
    fallbacks: [],
  },
  "cancel": {
    type: "button",
    preferred: "css=#filter-cancel-handler",
    fallbacks: ["role=button[name=/Cancel/i]","text=/Cancel/i"],
  },
  "checkboxLabel": {
    type: "checkbox",
    preferred: "css=#chkbox-id",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "checkboxLabel2": {
    type: "checkbox",
    preferred: "css=#select-all-hosts-groups-handler",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "checkboxLabel3": {
    type: "checkbox",
    preferred: "css=#select-all-vendor-groups-handler",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "checkboxLabel4": {
    type: "checkbox",
    preferred: "css=#select-all-vendor-leg-handler",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "clear": {
    type: "button",
    preferred: "css=#clear-filters-handler",
    fallbacks: ["role=button[name=/Clear/i]","text=/Clear/i"],
  },
  "closePreferenceCenter": {
    type: "button",
    preferred: "css=#close-pc-btn-handler",
    fallbacks: ["css=button[aria-label=\"Close preference center\"]","role=button[name=/Close preference center/i]"],
  },
  "closePreferences": {
    type: "button",
    preferred: "css=button[aria-label=\"Close Preferences\"]",
    fallbacks: ["role=button[name=/Close Preferences/i]"],
  },
  "complaints": {
    type: "link",
    preferred: "css=#complaints",
    fallbacks: ["role=link[name=/Complaints/i]","text=/Complaints/i"],
  },
  "complaints2": {
    type: "link",
    preferred: "css=#complaints",
    fallbacks: ["role=link[name=/Complaints/i]","text=/Complaints/i"],
  },
  "confirmMyChoices": {
    type: "button",
    preferred: "role=button[name=/Confirm My Choices/i]",
    fallbacks: ["text=/Confirm My Choices/i"],
  },
  "directdebitaccountnumbercollapselabeloutput": {
    type: "input",
    preferred: "css=#directDebitAccountNumberCollapseLabelOutput",
    fallbacks: ["role=textbox[name=/directDebitAccountNumberCollapseLabelOutput/i]"],
  },
  "directDebitGuarantee": {
    type: "link",
    preferred: "role=link[name=/Direct Debit Guarantee\\./i]",
    fallbacks: ["text=/Direct Debit Guarantee\\./i"],
  },
  "filterVendorsList": {
    type: "button",
    preferred: "css=#filter-btn-handler",
    fallbacks: ["css=button[aria-label=\"Filter Vendors List\"]","role=button[name=/Filter Icon/i]","text=/Filter Icon/i"],
  },
  "functionalCookies": {
    type: "button",
    preferred: "role=button[name=/Functional cookies/i]",
    fallbacks: [],
  },
  "functionalCookies2": {
    type: "checkbox",
    preferred: "css=#ot-group-id-3",
    fallbacks: ["css=input[name=\"ot-group-id-3\"]","role=switch[name=/Functional cookies/i]"],
  },
  "functionalCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Functional cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "iConfirmTheAboveStatementAboutTheConsumerCreditAgreement": {
    type: "checkbox",
    preferred: "css=#confirmDirectDebit",
    fallbacks: ["css=input[name=\"confirmDirectDebit\"]","role=textbox[name=/I confirm the above statement about the Consumer Credit Agreement/i]"],
  },
  "iConfirmTheNameOfTheAccountHolderAccountNumberAndSortCodeAreCorrectIAmAlsoAuthorisedToSetUpDirectDebitsFromThisAccount": {
    type: "checkbox",
    preferred: "css=#confirmDirectDebitAccountInformation",
    fallbacks: ["css=input[name=\"confirmDirectDebitAccountInformation\"]","role=textbox[name=/I confirm, the name of the account holder, account number and sort code are correct\\.I am also authorised to set up Direct Debits from this account\\./i]"],
  },
  "linkToAllianzHomePage": {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]","role=link[name=/Link to Allianz home page/i]"],
  },
  "manageCookies": {
    type: "button",
    preferred: "css=button[aria-label=\"Manage Cookies\"]",
    fallbacks: ["role=button[name=/Manage Cookies/i]"],
  },
  "moreInformationAboutYourPrivacyOpensInANewTab": {
    type: "link",
    preferred: "css=a[aria-label=\"More information about your privacy, opens in a new tab\"]",
    fallbacks: ["role=link[name=/More information/i]","text=/More information/i"],
  },
  "next": {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]","text=/Next/i"],
  },
  "noAmendMyDetails": {
    type: "link",
    preferred: "role=link[name=/No, amend my details/i]",
    fallbacks: ["text=/No, amend my details/i"],
  },
  "noAmendMyDetails2": {
    type: "link",
    preferred: "role=link[name=/No, amend my details/i]",
    fallbacks: ["text=/No, amend my details/i"],
  },
  "openTrustSeal": {
    type: "button",
    preferred: "css=button[aria-label=\"Open Trust Seal\"]",
    fallbacks: ["role=button[name=/Open Trust Seal/i]"],
  },
  "ourCookiePolicy": {
    type: "link",
    preferred: "css=#cookie-policy",
    fallbacks: ["role=link[name=/Our cookie policy/i]","text=/Our cookie policy/i"],
  },
  "ourCookiePolicy2": {
    type: "link",
    preferred: "css=#cookie-policy",
    fallbacks: ["role=link[name=/Our cookie policy/i]","text=/Our cookie policy/i"],
  },
  "ourFaqs": {
    type: "link",
    preferred: "role=link[name=/Our FAQs/i]",
    fallbacks: ["text=/Our FAQs/i"],
  },
  "performanceCookies": {
    type: "button",
    preferred: "role=button[name=/Performance cookies/i]",
    fallbacks: [],
  },
  "performanceCookies2": {
    type: "checkbox",
    preferred: "css=#ot-group-id-2",
    fallbacks: ["css=input[name=\"ot-group-id-2\"]","role=switch[name=/Performance cookies/i]"],
  },
  "performanceCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Performance cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "personalDataRights": {
    type: "link",
    preferred: "css=#data-rights",
    fallbacks: ["role=link[name=/Personal data rights/i]","text=/Personal data rights/i"],
  },
  "personalDataRights2": {
    type: "link",
    preferred: "css=#data-rights",
    fallbacks: ["role=link[name=/Personal data rights/i]","text=/Personal data rights/i"],
  },
  "poweredByOnetrustOpensInANewTab": {
    type: "link",
    preferred: "css=a[aria-label=\"Powered by OneTrust Opens in a new Tab\"]",
    fallbacks: ["role=link[name=/Powered by OneTrust Opens in a new Tab/i]"],
  },
  "preContractCreditAgreement": {
    type: "link",
    preferred: "role=link[name=/Pre-contract credit agreement/i]",
    fallbacks: ["text=/Pre-contract credit agreement/i"],
  },
  "sortcodeinputwithinfoquestionmonthpart": {
    type: "input",
    preferred: "css=#sortCodeInputWithInfoQuestionmonthPart",
    fallbacks: ["role=textbox[name=/sortCodeInputWithInfoQuestionmonthPart/i]"],
  },
  "sortcodeinputwithinfoquestionrandompart": {
    type: "input",
    preferred: "css=#sortCodeInputWithInfoQuestionrandomPart",
    fallbacks: ["role=textbox[name=/sortCodeInputWithInfoQuestionrandomPart/i]"],
  },
  "sortcodeinputwithinfoquestionrandompart2": {
    type: "input",
    preferred: "css=#sortCodeInputWithInfoQuestionrandomPart",
    fallbacks: ["role=textbox[name=/sortCodeInputWithInfoQuestionrandomPart/i]"],
  },
  "strictlyNecessaryCookiesAlwaysActive": {
    type: "button",
    preferred: "role=button[name=/Strictly Necessary cookies Always Active/i]",
    fallbacks: [],
  },
  "strictlyNecessaryCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Strictly Necessary cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "targetingCookies": {
    type: "button",
    preferred: "role=button[name=/Targeting cookies/i]",
    fallbacks: [],
  },
  "targetingCookies2": {
    type: "checkbox",
    preferred: "css=#ot-group-id-4",
    fallbacks: ["css=input[name=\"ot-group-id-4\"]","role=switch[name=/Targeting cookies/i]"],
  },
  "targetingCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Targeting cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "vendorListSearch": {
    type: "input",
    preferred: "css=#vendor-search-handler",
    fallbacks: ["css=input[name=\"vendor-search-handler\"]","css=input[aria-label=\"Vendor list search\"]","css=input[placeholder=\"Search vendors\"]","role=textbox[name=/Vendor list search/i]"],
  },
  "viewPaymentPlan": {
    type: "button",
    preferred: "role=button[name=/\\+ View payment plan/i]",
    fallbacks: ["text=/\\+ View payment plan/i"],
  },
  "whichDayOfTheMonthShouldWeTakeYourPayment": {
    type: "select",
    preferred: "css=#selectPaymentDay",
    fallbacks: ["role=combobox[name=/Which day of the month should we take your payment\\?/i]"],
  },
  "yesMyDetailsAreCorrect": {
    type: "button",
    preferred: "role=button[name=/Yes, my details are correct/i]",
    fallbacks: ["text=/Yes, my details are correct/i"],
  },
} as const;

export type ElementKey = keyof typeof elements;
