// src/toolingLayer/pageObjects/common/generatedFiles/buildGeneratedHeader.ts

import path from "node:path";
import {
    PAGE_OBJECTS_ROOT_DIR,
    toRepoRelative,
} from "@utils/paths";

function buildPageObjectPath(parts: string[]): string {
    return toRepoRelative(path.join(PAGE_OBJECTS_ROOT_DIR, ...parts));
}

export function headerFilePath(parts: string[]): string {
    return `// ${buildPageObjectPath(parts)}`;
}

export function headerGeneratedBy(source: string): string {
    return `// AUTO-GENERATED by ${source}`;
}

export function headerScaffoldedBy(source: string): string {
    return `// AUTO-SCAFFOLDED (create-only) by ${source}`;
}

export function headerGeneratedFromManifest(): string {
    const manifestPath = buildPageObjectPath([".manifest"]);
    return `// AUTO-GENERATED from ${manifestPath}/`;
}

export function getPageObjectFileParts(
    pageKey: string,
    fileName: string
): string[] {
    return ["objects", ...pageKey.split("."), fileName];
}

export function getPageManagerFileParts(): string[] {
    return ["pageManager.ts"];
}

export function getIndexFileParts(): string[] {
    return ["index.ts"];
}
