// src/pages/common/login-or-registration/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: common.login-or-registration
// scannedAt: 2026-03-09T12:48:41.552Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "common.login-or-registration",
  urlPath: "/",
  urlRe: new RegExp("^/$", "i"),
  title: "Allianz login page",
  titleRe: new RegExp("Allianz login page", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  logIn: "logIn" as ElementKey,
  register: "register" as ElementKey,
  skipThisStepILlRegisterLater: "skipThisStepILlRegisterLater" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;