// AUTO-GENERATED by src/scanner/generateElements.ts
// pageKey: common.account-registration
// scannedAt: 2026-02-27T11:53:33.156Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: string[];
};

export const elements = {
  "acceptAll": {
    type: "button",
    preferred: "css=#onetrust-accept-btn-handler",
    fallbacks: ["role=button[name=/Accept All/i]","text=/Accept All/i"],
  },
  "allowAll": {
    type: "button",
    preferred: "css=#accept-recommended-btn-handler",
    fallbacks: ["role=button[name=/Allow All/i]","text=/Allow All/i"],
  },
  "appleSignInBtn": {
    type: "button",
    preferred: "css=#apple-sign-in-btn",
    fallbacks: ["role=button[name=/apple-sign-in-btn/i]"],
  },
  "apply": {
    type: "button",
    preferred: "css=#filter-apply-handler",
    fallbacks: ["role=button[name=/Apply/i]","text=/Apply/i"],
  },
  "back": {
    type: "button",
    preferred: "role=button[name=/Back/i]",
    fallbacks: ["text=/Back/i"],
  },
  "back2": {
    type: "button",
    preferred: "css=button[aria-label=\"Back\"]",
    fallbacks: ["role=button[name=/Back Button/i]","text=/Back Button/i"],
  },
  "cancel": {
    type: "button",
    preferred: "css=#cancel-apple-sign-in-btn",
    fallbacks: ["role=button[name=/Cancel/i]","text=/Cancel/i"],
  },
  "cancel2": {
    type: "button",
    preferred: "css=#filter-cancel-handler",
    fallbacks: ["role=button[name=/Cancel/i]","text=/Cancel/i"],
  },
  "checkboxLabel": {
    type: "checkbox",
    preferred: "css=#chkbox-id",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "checkboxLabel2": {
    type: "checkbox",
    preferred: "css=#select-all-hosts-groups-handler",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "checkboxLabel3": {
    type: "checkbox",
    preferred: "css=#select-all-vendor-groups-handler",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "checkboxLabel4": {
    type: "checkbox",
    preferred: "css=#select-all-vendor-leg-handler",
    fallbacks: ["role=textbox[name=/checkbox label/i]"],
  },
  "clear": {
    type: "button",
    preferred: "css=#clear-filters-handler",
    fallbacks: ["role=button[name=/Clear/i]","text=/Clear/i"],
  },
  "closeAppleWarningBtn": {
    type: "button",
    preferred: "css=#close-apple-warning-btn",
    fallbacks: ["role=button[name=/close-apple-warning-btn/i]"],
  },
  "closePreferenceCenter": {
    type: "button",
    preferred: "css=#close-pc-btn-handler",
    fallbacks: ["css=button[aria-label=\"Close preference center\"]","role=button[name=/Close preference center/i]"],
  },
  "closePreferences": {
    type: "button",
    preferred: "css=button[aria-label=\"Close Preferences\"]",
    fallbacks: ["role=button[name=/Close Preferences/i]"],
  },
  "complaints": {
    type: "link",
    preferred: "css=#complaints",
    fallbacks: ["role=link[name=/Complaints/i]","text=/Complaints/i"],
  },
  "confirmMyChoices": {
    type: "button",
    preferred: "role=button[name=/Confirm My Choices/i]",
    fallbacks: ["text=/Confirm My Choices/i"],
  },
  "confirmNewPassword": {
    type: "input",
    preferred: "css=#password-confirm",
    fallbacks: ["css=input[name=\"password-confirm\"]","css=input[aria-label=\"Password confirmation input field\"]","role=textbox[name=/Password confirmation input field/i]"],
  },
  "createAccount": {
    type: "button",
    preferred: "css=#register-form-submit",
    fallbacks: ["role=button[name=/Create account/i]","text=/Create account/i"],
  },
  "createPassword": {
    type: "input",
    preferred: "css=#password",
    fallbacks: ["css=input[name=\"password\"]","css=input[aria-label=\"Password input field\"]","role=textbox[name=/Password input field/i]"],
  },
  "emailAddress": {
    type: "input",
    preferred: "css=#email",
    fallbacks: ["css=input[name=\"email\"]","css=input[aria-label=\"Email address input field\"]","css=input[placeholder=\"email@gmail.com\"]","role=textbox[name=/Email address input field/i]"],
  },
  "filterVendorsList": {
    type: "button",
    preferred: "css=#filter-btn-handler",
    fallbacks: ["css=button[aria-label=\"Filter Vendors List\"]","role=button[name=/Filter Icon/i]","text=/Filter Icon/i"],
  },
  "functionalCookies": {
    type: "button",
    preferred: "role=button[name=/Functional cookies/i]",
    fallbacks: [],
  },
  "functionalCookies2": {
    type: "checkbox",
    preferred: "css=#ot-group-id-3",
    fallbacks: ["css=input[name=\"ot-group-id-3\"]","role=switch[name=/Functional cookies/i]"],
  },
  "functionalCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Functional cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "googleSignInBtn": {
    type: "button",
    preferred: "css=#google-sign-in-btn",
    fallbacks: ["role=button[name=/google-sign-in-btn/i]"],
  },
  "here": {
    type: "link",
    preferred: "css=#change-email-link",
    fallbacks: ["role=link[name=/here/i]","text=/here/i"],
  },
  "linkToAllianzHomePage": {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]","role=link[name=/Link to Allianz home page/i]"],
  },
  "logIn": {
    type: "link",
    preferred: "role=link[name=/Log in/i]",
    fallbacks: ["text=/Log in/i"],
  },
  "manageCookies": {
    type: "button",
    preferred: "css=button[aria-label=\"Manage Cookies\"]",
    fallbacks: ["role=button[name=/Manage Cookies/i]"],
  },
  "manageCookiesOpensThePreferenceCenterDialog": {
    type: "button",
    preferred: "css=#onetrust-pc-btn-handler",
    fallbacks: ["css=button[aria-label=\"Manage Cookies, Opens the preference center dialog\"]","role=button[name=/Manage Cookies/i]","text=/Manage Cookies/i"],
  },
  "moreInformationAboutYourPrivacyOpensInANewTab": {
    type: "link",
    preferred: "css=a[aria-label=\"More information about your privacy, opens in a new tab\"]",
    fallbacks: ["role=link[name=/Refer to our Cookie Policy/i]","text=/Refer to our Cookie Policy/i"],
  },
  "moreInformationAboutYourPrivacyOpensInANewTab2": {
    type: "link",
    preferred: "css=a[aria-label=\"More information about your privacy, opens in a new tab\"]",
    fallbacks: ["role=link[name=/More information/i]","text=/More information/i"],
  },
  "okayIUnderstand": {
    type: "button",
    preferred: "css=#confirm-apple-sign-in-btn",
    fallbacks: ["role=button[name=/Okay, I understand/i]","text=/Okay, I understand/i"],
  },
  "openKeeperPopup": {
    type: "button",
    preferred: "css=#k-piw2ea3r6xd",
    fallbacks: ["css=keeper-lock[aria-label=\"Open Keeper Popup\"]","role=button[name=/Open Keeper Popup/i]"],
  },
  "openKeeperPopup2": {
    type: "button",
    preferred: "css=#k-6bewafp3uf4",
    fallbacks: ["css=keeper-lock[aria-label=\"Open Keeper Popup\"]","role=button[name=/Open Keeper Popup/i]"],
  },
  "openKeeperPopup3": {
    type: "button",
    preferred: "css=#k-wo1qiubp2nq",
    fallbacks: ["css=keeper-lock[aria-label=\"Open Keeper Popup\"]","role=button[name=/Open Keeper Popup/i]"],
  },
  "ourCookiePolicy": {
    type: "link",
    preferred: "css=#cookie-policy",
    fallbacks: ["role=link[name=/Our cookie policy/i]","text=/Our cookie policy/i"],
  },
  "performanceCookies": {
    type: "button",
    preferred: "role=button[name=/Performance cookies/i]",
    fallbacks: [],
  },
  "performanceCookies2": {
    type: "checkbox",
    preferred: "css=#ot-group-id-2",
    fallbacks: ["css=input[name=\"ot-group-id-2\"]","role=switch[name=/Performance cookies/i]"],
  },
  "performanceCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Performance cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "personalDataRights": {
    type: "link",
    preferred: "css=#data-rights",
    fallbacks: ["role=link[name=/Personal data rights/i]","text=/Personal data rights/i"],
  },
  "poweredByOnetrustOpensInANewTab": {
    type: "link",
    preferred: "css=a[aria-label=\"Powered by OneTrust Opens in a new Tab\"]",
    fallbacks: ["role=link[name=/Powered by OneTrust Opens in a new Tab/i]"],
  },
  "rejectAll": {
    type: "button",
    preferred: "css=#onetrust-reject-all-handler",
    fallbacks: ["role=button[name=/Reject All/i]","text=/Reject All/i"],
  },
  "strictlyNecessaryCookiesAlwaysActive": {
    type: "button",
    preferred: "role=button[name=/Strictly Necessary cookies Always Active/i]",
    fallbacks: [],
  },
  "strictlyNecessaryCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Strictly Necessary cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "targetingCookies": {
    type: "button",
    preferred: "role=button[name=/Targeting cookies/i]",
    fallbacks: [],
  },
  "targetingCookies2": {
    type: "checkbox",
    preferred: "css=#ot-group-id-4",
    fallbacks: ["css=input[name=\"ot-group-id-4\"]","role=switch[name=/Targeting cookies/i]"],
  },
  "targetingCookiesVendorDetailsButtonOpensVendorListMenu": {
    type: "button",
    preferred: "css=button[aria-label=\"Targeting cookies - Vendor Details button opens Vendor List menu\"]",
    fallbacks: ["role=button[name=/View Vendor Details‎/i]","text=/View Vendor Details‎/i"],
  },
  "vendorListSearch": {
    type: "input",
    preferred: "css=#vendor-search-handler",
    fallbacks: ["css=input[name=\"vendor-search-handler\"]","css=input[aria-label=\"Vendor list search\"]","css=input[placeholder=\"Search vendors\"]","role=textbox[name=/Vendor list search/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;
