// src/pages/motor/ph-no-claim-discount/aliases.generated.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ph-no-claim-discount
// scannedAt: 2026-03-09T13:02:53.695Z

import type { ElementKey } from "./elements";

// Page metadata (used for waitForURL / assertions)
export const pageMeta = {
  pageKey: "motor.ph-no-claim-discount",
  urlPath: "/journey/show/product/AnnualMotorInsurance/process/nb/ncd/69aec1fabe84b34399895bf0",
  urlRe: /\/journey\/show\/product\/AnnualMotorInsurance\/process\/nb\/ncd\/[a-z0-9]+/i,
  title: "No claim discount",
  titleRe: new RegExp("No claim discount", "i"),
} as const;

// Default alias mapping: alias key == element key
export const aliasesGenerated = {
  back: "back" as ElementKey,
  inAnotherCountry: "inAnotherCountry" as ElementKey,
  linkToAllianzHomePage: "linkToAllianzHomePage" as ElementKey,
  namedDriverOnAnotherPolicy: "namedDriverOnAnotherPolicy" as ElementKey,
  ncdyearsquestion: "ncdyearsquestion" as ElementKey,
  next: "next" as ElementKey,
  no: "no" as ElementKey,
  withACompanyCar: "withACompanyCar" as ElementKey,
  withThisCarSh11ukaOrAPreviousCar: "withThisCarSh11ukaOrAPreviousCar" as ElementKey,
  yes: "yes" as ElementKey,
} as const;

export type AliasGeneratedKey = keyof typeof aliasesGenerated;