// src/pages/motor/ph-no-claim-discount/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: motor.ph-no-claim-discount
// scannedAt: 2026-03-09T13:02:53.695Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  back: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  inAnotherCountry: {
    type: "radio",
    preferred: "css=#ncdEarnTypeQuestion4",
    fallbacks: ["css=input[name=\"ncdEarnTypeQuestion\"]", "role=textbox[name=/In another country/i]"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  namedDriverOnAnotherPolicy: {
    type: "radio",
    preferred: "css=#ncdEarnTypeQuestion3",
    fallbacks: ["css=input[name=\"ncdEarnTypeQuestion\"]", "role=textbox[name=/Named driver on another policy/i]"],
  },
  ncdyearsquestion: {
    type: "select",
    preferred: "css=#ncdYearsQuestion",
    fallbacks: ["role=combobox[name=/ncdYearsQuestion/i]"],
  },
  next: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  no: {
    type: "radio",
    preferred: "css=#protectedNcdQuestion-false",
    fallbacks: ["css=input[name=\"protectedNcdQuestion-false\"]", "role=textbox[name=/No/i]"],
  },
  withACompanyCar: {
    type: "radio",
    preferred: "css=#ncdEarnTypeQuestion2",
    fallbacks: ["css=input[name=\"ncdEarnTypeQuestion\"]", "role=textbox[name=/With a company car/i]"],
  },
  withThisCarSh11ukaOrAPreviousCar: {
    type: "radio",
    preferred: "css=#ncdEarnTypeQuestion1",
    fallbacks: ["css=input[name=\"ncdEarnTypeQuestion\"]", "role=textbox[name=/With this car \\(SH11UKA\\) or a previous car/i]"],
  },
  yes: {
    type: "radio",
    preferred: "css=#protectedNcdQuestion-true",
    fallbacks: ["css=input[name=\"protectedNcdQuestion-true\"]", "role=textbox[name=/Yes/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;