// src/pages/objects/athena/motor/ph-driving-licence-details/elements.ts
// AUTO-GENERATED by src/scanner/elements-generator
// pageKey: athena.motor.ph-driving-licence-details
// scannedAt: 2026-03-13T17:03:49.922Z

export type ElementDef = {
  type: string;
  preferred: string;
  fallbacks: readonly string[];
};

export const elements = {
  buttonAddAnotherConviction: {
    type: "button",
    preferred: "css=#addAnotherConvictionButton",
    fallbacks: ["css=button[name=\"addAnotherConvictionButton\"]", "role=button[name=/Add another conviction/i]", "text=/Add another conviction/i"],
  },
  buttonFindAddress: {
    type: "button",
    preferred: "css=#find-address",
    fallbacks: ["role=button[name=/Find address/i]", "text=/Find address/i"],
  },
  buttonNavigatorBack: {
    type: "button",
    preferred: "css=#navigatorBack",
    fallbacks: ["role=link[name=/Back/i]", "text=/Back/i"],
  },
  buttonNavigatorNext: {
    type: "button",
    preferred: "css=#navigatorNext",
    fallbacks: ["role=button[name=/Next/i]", "text=/Next/i"],
  },
  groupRadioConviction0ResultedToABan: {
    type: "radio-group",
    preferred: "",
    fallbacks: [],
  },
  groupRadioConviction1ResultedToABan: {
    type: "radio-group",
    preferred: "",
    fallbacks: [],
  },
  groupRadioConviction2ResultedToABan: {
    type: "radio-group",
    preferred: "",
    fallbacks: [],
  },
  groupRadioDrivingLicenceHandy: {
    type: "radio-group",
    preferred: "",
    fallbacks: [],
  },
  groupRadioDrivingLicenceTypes: {
    type: "radio-group",
    preferred: "",
    fallbacks: [],
  },
  groupRadioHasConvictionsQuestion: {
    type: "radio-group",
    preferred: "",
    fallbacks: [],
  },
  inputAddressLookupWidgetAddressLookupQuestionInputBuilding: {
    type: "input",
    preferred: "css=#addressLookupWidget-addressLookupQuestionInput-building",
    fallbacks: ["role=textbox[name=/addressLookupWidget-addressLookupQuestionInput-building/i]"],
  },
  inputAddressLookupWidgetAddressLookupQuestionInputPostcode: {
    type: "input",
    preferred: "css=#addressLookupWidget-addressLookupQuestionInput-postcode",
    fallbacks: ["role=textbox[name=/addressLookupWidget-addressLookupQuestionInput-postcode/i]"],
  },
  inputConviction1DateMonth: {
    type: "input",
    preferred: "css=#conviction_1_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  inputConviction1DateYear: {
    type: "input",
    preferred: "css=#conviction_1_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  inputConviction2DateMonth: {
    type: "input",
    preferred: "css=#conviction_2_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  inputConviction2DateYear: {
    type: "input",
    preferred: "css=#conviction_2_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  inputConviction3DateMonth: {
    type: "input",
    preferred: "css=#conviction_3_date-month",
    fallbacks: ["css=input[aria-label=\"Month input field\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/Month input field/i]"],
  },
  inputConviction3DateYear: {
    type: "input",
    preferred: "css=#conviction_3_date-year",
    fallbacks: ["css=input[aria-label=\"Year input field\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/Year input field/i]"],
  },
  inputDateOfBirthDay: {
    type: "input",
    preferred: "css=#dateOfBirth-day",
    fallbacks: ["css=input[aria-label=\"day\"]", "css=input[placeholder=\"DD\"]", "role=textbox[name=/day/i]"],
  },
  inputDateOfBirthMonth: {
    type: "input",
    preferred: "css=#dateOfBirth-month",
    fallbacks: ["css=input[aria-label=\"month\"]", "css=input[placeholder=\"MM\"]", "role=textbox[name=/month/i]"],
  },
  inputDateOfBirthYear: {
    type: "input",
    preferred: "css=#dateOfBirth-year",
    fallbacks: ["css=input[aria-label=\"year\"]", "css=input[placeholder=\"YYYY\"]", "role=textbox[name=/year/i]"],
  },
  inputFirstName: {
    type: "input",
    preferred: "css=#firstName",
    fallbacks: ["role=textbox[name=/First name/i]"],
  },
  inputLastName: {
    type: "input",
    preferred: "css=#lastName",
    fallbacks: ["role=textbox[name=/Last name/i]"],
  },
  linkRemoveConviction: {
    type: "link",
    preferred: "role=link[name=/Remove conviction/i]",
    fallbacks: ["text=/Remove conviction/i"],
  },
  linkRemoveConviction2: {
    type: "link",
    preferred: "role=link[name=/Remove conviction/i]",
    fallbacks: ["text=/Remove conviction/i"],
  },
  linkRemoveConviction3: {
    type: "link",
    preferred: "role=link[name=/Remove conviction/i]",
    fallbacks: ["text=/Remove conviction/i"],
  },
  linkToAllianzHomePage: {
    type: "link",
    preferred: "css=#goToAllianzHomePage",
    fallbacks: ["css=a[aria-label=\"Link to Allianz home page\"]", "role=link[name=/Link to Allianz home page/i]"],
  },
  radioConviction0ResultedToABanno: {
    type: "radio",
    preferred: "css=#Conviction0ResultedToABanfalse",
    fallbacks: ["css=input[name=\"Conviction0ResultedToABan\"]", "role=textbox[name=/No/i]"],
  },
  radioConviction0ResultedToABanyes: {
    type: "radio",
    preferred: "css=#Conviction0ResultedToABantrue",
    fallbacks: ["css=input[name=\"Conviction0ResultedToABan\"]", "role=textbox[name=/Yes/i]"],
  },
  radioConviction1ResultedToABanno: {
    type: "radio",
    preferred: "css=#Conviction1ResultedToABanfalse",
    fallbacks: ["css=input[name=\"Conviction1ResultedToABan\"]", "role=textbox[name=/No/i]"],
  },
  radioConviction1ResultedToABanyes: {
    type: "radio",
    preferred: "css=#Conviction1ResultedToABantrue",
    fallbacks: ["css=input[name=\"Conviction1ResultedToABan\"]", "role=textbox[name=/Yes/i]"],
  },
  radioConviction2ResultedToABanno: {
    type: "radio",
    preferred: "css=#Conviction2ResultedToABanfalse",
    fallbacks: ["css=input[name=\"Conviction2ResultedToABan\"]", "role=textbox[name=/No/i]"],
  },
  radioConviction2ResultedToABanyes: {
    type: "radio",
    preferred: "css=#Conviction2ResultedToABantrue",
    fallbacks: ["css=input[name=\"Conviction2ResultedToABan\"]", "role=textbox[name=/Yes/i]"],
  },
  radioDrivingLicenceHandyno: {
    type: "radio",
    preferred: "css=#drivingLicenceHandyfalse",
    fallbacks: ["css=input[name=\"drivingLicenceHandy\"]", "role=textbox[name=/No/i]"],
  },
  radioDrivingLicenceHandyyes: {
    type: "radio",
    preferred: "css=#drivingLicenceHandytrue",
    fallbacks: ["css=input[name=\"drivingLicenceHandy\"]", "role=textbox[name=/Yes/i]"],
  },
  radioDrivingLicenceTypeseuFull: {
    type: "radio",
    preferred: "css=#drivingLicenceTypes4",
    fallbacks: ["css=input[name=\"drivingLicenceTypes\"]", "role=textbox[name=/EU Full/i]"],
  },
  radioDrivingLicenceTypeseuProvisional: {
    type: "radio",
    preferred: "css=#drivingLicenceTypes5",
    fallbacks: ["css=input[name=\"drivingLicenceTypes\"]", "role=textbox[name=/EU Provisional/i]"],
  },
  radioDrivingLicenceTypesother: {
    type: "radio",
    preferred: "css=#drivingLicenceTypes6",
    fallbacks: ["css=input[name=\"drivingLicenceTypes\"]", "role=textbox[name=/Other/i]"],
  },
  radioDrivingLicenceTypesukFull: {
    type: "radio",
    preferred: "css=#drivingLicenceTypes1",
    fallbacks: ["css=input[name=\"drivingLicenceTypes\"]", "role=textbox[name=/UK Full/i]"],
  },
  radioDrivingLicenceTypesukFullAutomaticOnly: {
    type: "radio",
    preferred: "css=#drivingLicenceTypes2",
    fallbacks: ["css=input[name=\"drivingLicenceTypes\"]", "role=textbox[name=/UK Full - Automatic only/i]"],
  },
  radioDrivingLicenceTypesukProvisional: {
    type: "radio",
    preferred: "css=#drivingLicenceTypes3",
    fallbacks: ["css=input[name=\"drivingLicenceTypes\"]", "role=textbox[name=/UK Provisional/i]"],
  },
  radioHasConvictionsQuestionno: {
    type: "radio",
    preferred: "css=#hasConvictionsQuestionfalse",
    fallbacks: ["css=input[name=\"hasConvictionsQuestion\"]", "role=textbox[name=/No/i]"],
  },
  radioHasConvictionsQuestionyes: {
    type: "radio",
    preferred: "css=#hasConvictionsQuestiontrue",
    fallbacks: ["css=input[name=\"hasConvictionsQuestion\"]", "role=textbox[name=/Yes/i]"],
  },
  searchSelectTheConvictionCode: {
    type: "input",
    preferred: "css=#react-select-2-input",
    fallbacks: ["role=textbox[name=/react-select-2-input/i]"],
  },
  searchSelectTheConvictionCode2: {
    type: "input",
    preferred: "css=#react-select-3-input",
    fallbacks: ["role=textbox[name=/react-select-3-input/i]"],
  },
  searchSelectTheConvictionCode3: {
    type: "input",
    preferred: "css=#react-select-4-input",
    fallbacks: ["role=textbox[name=/react-select-4-input/i]"],
  },
  selectAddressLookupQuestionInput: {
    type: "select",
    preferred: "css=#addressLookupQuestionInput",
    fallbacks: ["role=combobox[name=/Address/i]"],
  },
  selectDrivingExpirience: {
    type: "select",
    preferred: "css=#drivingExpirience",
    fallbacks: ["role=combobox[name=/How long have you held your licence for\\?/i]"],
  },
  selectTitleQuestion: {
    type: "select",
    preferred: "css=#titleQuestion",
    fallbacks: ["role=combobox[name=/Title/i]"],
  },
} as const;

export type ElementKey = keyof typeof elements;