// src/toolingLayer/pageActions/common/registry/buildApplicationIndexContent.ts

import { toRepoRelative } from "@utils/paths";

export function buildApplicationIndexContent(
    filePath: string,
    products: string[]
): string {
    return [
        `// ${toRepoRelative(filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        ...products.map((product) => `export * from "./${product}";`),
        ``,
    ].join("\n");
}
