// src/toolingLayer/pageActions/common/registry/buildProductIndexContent.ts

import { toRepoRelative } from "@utils/paths";
import type { ActionRegistryEntry } from "../../generator/shared/types";

export function buildProductIndexContent(
    filePath: string,
    entries: ActionRegistryEntry[]
): string {
    const lines = entries
        .slice()
        .sort((a, b) => a.pageKey.localeCompare(b.pageKey))
        .map((entry) => {
            const importPath = `./${entry.actionFileName.replace(".ts", "")}`;
            return `export { ${entry.actionName} } from "${importPath}";`;
        });

    return [
        `// ${toRepoRelative(filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        ...lines,
        ``,
    ].join("\n");
}
