// src/toolingLayer/pageActions/common/registry/buildPlatformIndexContent.ts

import { toRepoRelative } from "@utils/paths";

export function buildPlatformIndexContent(
    filePath: string,
    applications: string[]
): string {
    return [
        `// ${toRepoRelative(filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        ...applications.map(
            (application) => `export * from "./${application}";`
        ),
        ``,
    ].join("\n");
}
