// src/toolingLayer/pageActions/common/registry/buildRootIndexContent.ts

import { toRepoRelative } from "@utils/paths";

export function buildRootIndexContent(filePath: string): string {
    return [
        `// ${toRepoRelative(filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        `export * from "./shared";`,
        `export * from "./actions";`,
        ``,
    ].join("\n");
}
