// src/toolingLayer/pageActions/common/registry/buildActionsIndexContent.ts

import { toRepoRelative } from "@utils/paths";

export function buildActionsIndexContent(
    filePath: string,
    platforms: string[]
): string {
    return [
        `// ${toRepoRelative(filePath)}`,
        `// AUTO-GENERATED by pageActions generator`,
        ``,
        ...platforms.map((platform) => `export * from "./${platform}";`),
        ``,
    ].join("\n");
}
